from pathlib import Path

edits = {
	'tests/setup.ts': [
		(' * Narrow an untyped value to an', ' * Narrows an untyped value to an'),
		(' * Await one promise within a bounded', ' * Awaits one promise within a bounded'),
		(' * Build a well-formed {@link JSONRPCRequest}', ' * Builds a well-formed {@link JSONRPCRequest}'),
		(' * Build a JSON-RPC notification whose', ' * Builds a JSON-RPC notification whose'),
		(' * Build one adversarial corpus every', ' * Builds one adversarial corpus every'),
		('/** Every key name the published guards read off an untrusted value by name. */',
		 '/** Lists every key name the published guards read off an untrusted value by name. */'),
		('/** The accessor body every throwing-key row installs. */',
		 '/** Throws as the accessor body every throwing-key row installs. */'),
		(' * Build one record per key, each defining', ' * Builds one record per key, each defining'),
		(' * Build the canonical calculator {@link MCPServerInterface}', ' * Builds the canonical calculator {@link MCPServerInterface}'),
		(' * Build an {@link MCPServerInterface} whose every', ' * Builds an {@link MCPServerInterface} whose every'),
		('/** The reserved `_meta` a modern request carries — the protocol version plus empty capabilities. */',
		 '/** Supplies the reserved `_meta` a modern request carries — the protocol version plus empty capabilities. */'),
		('/** One row of the protocol-version projection both HTTP client transports must answer alike. */',
		 '/** Describes one row of the protocol-version projection both HTTP client transports must answer alike. */'),
		('/** The shared modern-context table both HTTP client transports are driven over. */',
		 '/** Supplies the shared modern-context table both HTTP client transports are driven over. */'),
		(" * Build one `tools/list` request for the header-projection table.", " * Builds one `tools/list` request for the header-projection table."),
		(' * Build a modern request carrying the shared', ' * Builds a modern request carrying the shared'),
		('/** In-memory resource manager shared by server and legacy dispatch tests. */',
		 '/** Serves resources from memory for the server and legacy dispatch tests. */'),
		('/** A peerable in-memory transport with outbound recording. */',
		 '/** Describes a peerable in-memory transport with outbound recording. */'),
		(' * Create a peerable in-memory MCP transport.', ' * Creates a peerable in-memory MCP transport.'),
		('/** A minimal protocol peer that exchanges serialized JSON-RPC over the real duplex port. */',
		 '/** Describes a minimal protocol peer that exchanges serialized JSON-RPC over the real duplex port. */'),
		(' * Bind an MCP server to a minimal serialized-message peer.', ' * Binds an MCP server to a minimal serialized-message peer.'),
		(' * Build one modern `subscriptions/listen` request', ' * Builds one modern `subscriptions/listen` request'),
		('/** What one consumer did with the controlled exchange it was handed. */',
		 '/** Reports what one consumer did with the controlled exchange it was handed. */'),
		(' * Hand one controlled exchange to a consumer and report whether that consumer ENDED it.',
		 ' * Hands one controlled exchange to a consumer and reports whether that consumer ENDED it.'),
		('/** The owner-of-last-resort spellings a controlled exchange must never grow. */',
		 '/** Lists the owner-of-last-resort spellings a controlled exchange must never grow. */'),
		(' * Report every owner-of-last-resort construct a source declares.',
		 ' * Reports every owner-of-last-resort construct a source declares.'),
		(' * Drive one client-initiated notification through a live carrier and report what the peer got.',
		 ' * Drives one client-initiated notification through a live carrier and reports what the peer got.'),
		(' * Read the `method` of every invocation among', ' * Reads the `method` of every invocation among'),
		(' * Create an in-process {@link MCPMessageTransportInterface} that dispatches directly against a',
		 ' * Dispatches directly against a given {@link MCPServerInterface} from an in-process'),
		(' * POST a JSON value to a real HTTP fixture endpoint.', ' * Posts a JSON value to a real HTTP fixture endpoint.'),
		(" * Drain a `fetch` Response's SSE body to completion", " * Drains a `fetch` Response's SSE body to completion"),
		(" * Stream a `fetch` Response's SSE body as decoded", " * Streams a `fetch` Response's SSE body as decoded"),
		('/** A manually-driven epoch-ms clock plus the control to advance it explicitly. */',
		 '/** Describes a manually-driven epoch-ms clock plus the control to advance it explicitly. */'),
		(' * Create a {@link ManualClockInterface} — a manual-time', ' * Creates a {@link ManualClockInterface} — a manual-time'),
		('/** One outbound frame, with the real instant it left the client. */',
		 '/** Describes one outbound frame, with the real instant it left the client. */'),
		('/** An {@link MCPMessageTransportInterface} that records every outbound frame and when it left. */',
		 '/** Records every outbound frame and when it left, as an {@link MCPMessageTransportInterface}. */'),
		(' * Create an in-process {@link TestTransportInterface} over a real', ' * Creates an in-process {@link TestTransportInterface} over a real'),
		(' * Create a real {@link MCPServerInterface} with the stable Tasks', ' * Creates a real {@link MCPServerInterface} with the stable Tasks'),
		('/** The client capabilities that declare the stable Tasks extension — the whole declaration. */',
		 '/** Declares the stable Tasks extension in the client capabilities — the whole declaration. */'),
		('/** How one {@link TestTaskManager} runs a task\'s work. */',
		 '/** Decides how one {@link TestTaskManager} runs a task\'s work. */'),
		(' * A real in-memory {@link MCPTaskManagerInterface} — a durable store, a worker per task,',
		 ' * Runs durable tasks in memory as a real {@link MCPTaskManagerInterface} — a durable store, a worker per task,'),
	],
	'tests/setupServer.ts': [
		(' * Find the imports Guide surfaces from a projected fence', ' * Finds the imports Guide surfaces from a projected fence'),
		(' * A structural guard narrowing an `unknown` stub to {@link', ' * Narrows an `unknown` stub structurally to {@link'),
		(' * Build a minimal `node:http`-shaped request stub', ' * Builds a minimal `node:http`-shaped request stub'),
		('/** Which fault a {@link createStreamStub} stream raises, if any. */',
		 '/** Selects which fault a {@link createStreamStub} stream raises, if any. */'),
		('/** A real {@link StreamInterface} that also reports what was written and whether it ended. */',
		 '/** Reports what was written to a real {@link StreamInterface} and whether it ended. */'),
		(' * Build a real SSE {@link StreamInterface} whose', ' * Builds a real SSE {@link StreamInterface} whose'),
		(' * Create a cross-wired in-memory `node:stream` Duplex PAIR', ' * Creates a cross-wired in-memory `node:stream` Duplex PAIR'),
		(" * Resolve on the socket pair's next tick or two", " * Resolves on the socket pair's next tick or two"),
		(" * Collect a {@link duplexPair} client end's incoming frames", " * Collects a {@link duplexPair} client end's incoming frames"),
		("/** A raw client socket held open against a real server's WebSocket endpoint. */",
		 "/** Holds a raw client socket open against a real server's WebSocket endpoint. */"),
		(' * Open a raw RFC 6455 client socket against a real server and decode what it sends back —',
		 ' * Opens a raw RFC 6455 client socket against a real server and decodes what it sends back —'),
		('/** A started test server — its bound `base` URL plus the `ServerInterface`. */',
		 "/** Pairs a started test server's bound `base` URL with its `ServerInterface`. */"),
		(' * Start a `ServerInterface` on an ephemeral port and resolve its bound base URL — the',
		 ' * Starts a `ServerInterface` on an ephemeral port and resolves its bound base URL — the'),
		(' * A test resource released through {@link closeResource}:', ' * Names a test resource released through {@link closeResource}:'),
		(' * Release one {@link TestResource} from a suite', ' * Releases one {@link TestResource} from a suite'),
		('/** The outcome of an {@link upgradeRequest} — whether the server claimed the upgrade. */',
		 '/** Reports the outcome of an {@link upgradeRequest} — whether the server claimed the upgrade. */'),
		(' * Create a middleware that advances a manual clock', ' * Creates a middleware that advances a manual clock'),
		(' * Create a middleware that holds every request open', ' * Creates a middleware that holds every request open'),
		('/** A raw upgrade peer — how many sockets it accepted, and how many are still open. */',
		 "/** Counts a raw upgrade peer's sockets — how many it accepted, and how many are still open. */"),
		('/** How a {@link startUpgradeServer} peer answers each upgrade. */',
		 '/** Decides how a {@link startUpgradeServer} peer answers each upgrade. */'),
		(' * Start a raw `node:http` peer that completes real', ' * Starts a raw `node:http` peer that completes real'),
	],
	'tests/setupBrowser.ts': [
		(' * Tap a live `MessagePort` and return a drain over the JSON-RPC frames it has received.',
		 ' * Taps a live `MessagePort` and returns a drain over the JSON-RPC frames it has received.'),
		('/** A wired pair of real `createScopeTransport` halves, plus what the SERVER half received. */',
		 '/** Wires a pair of real `createScopeTransport` halves, plus what the SERVER half received. */'),
		(' * Wire real {@link createScopeTransport} halves into one in-page duplex carrier.',
		 ' * Wires real {@link createScopeTransport} halves into one in-page duplex carrier.'),
		(" * Read (and clear) every frame the Node fixture's recording peers received.",
		 " * Reads (and clears) every frame the Node fixture's recording peers received."),
	],
	'tests/setupGlobal.ts': [
		("/** The runnable export loaded into the fixture's isolated Node-side Vite graph. */",
		 "/** Describes the runnable export loaded into the fixture's isolated Node-side Vite graph. */"),
		('/** Narrow the isolated fixture module before invoking its setup export. */',
		 '/** Narrows the isolated fixture module before invoking its setup export. */'),
		(' * Start the external Node fixture before Chromium receives the browser test graph.',
		 ' * Starts the external Node fixture before Chromium receives the browser test graph.'),
	],
	'tests/fixtures/browserServer.ts': [
		("/** The running Node fixture exposed to the browser project's global setup. */",
		 "/** Describes the running Node fixture exposed to the browser project's global setup. */"),
		('/** Create the intentionally malformed JSON response used by the HTTP error-path test. */',
		 '/** Creates the intentionally malformed JSON response used by the HTTP error-path test. */'),
		('/** Let the real browser page reach the external HTTP fixture, including session requests. */',
		 '/** Lets the real browser page reach the external HTTP fixture, including session requests. */'),
		(' * Record one raw frame a fixture peer received.', ' * Records one raw frame a fixture peer received.'),
		(' * Answer with every recorded frame and clear the log.', ' * Answers with every recorded frame and clears the log.'),
		(' * Answer a POST with the MCP headers it actually carried across the wire.',
		 ' * Answers a POST with the MCP headers it actually carried across the wire.'),
		(' * Record every JSON-RPC body POSTed to the fixture before the route handles it.',
		 ' * Records every JSON-RPC body POSTed to the fixture before the route handles it.'),
		(' * Create the recording WebSocket peer — the REAL server', ' * Creates the recording WebSocket peer — the REAL server'),
		('/** Create raw WebSocket endpoints for peer-close and malformed-frame browser tests. */',
		 '/** Creates raw WebSocket endpoints for peer-close and malformed-frame browser tests. */'),
		(' * Start the real MCP HTTP/session/WebSocket fixture on an ephemeral loopback port.',
		 ' * Starts the real MCP HTTP/session/WebSocket fixture on an ephemeral loopback port.'),
	],
	'tests/setupConformance.ts': [
		('/** The conformance runner package, pinned as a development dependency and resolved from disk. */',
		 '/** Names the conformance runner package, pinned as a development dependency and resolved from disk. */'),
		("/** The runner's entry module inside its installed package. */",
		 "/** Names the runner's entry module inside its installed package. */"),
		('/** The dated protocol revision the runner drives the server at. */',
		 '/** Names the dated protocol revision the runner drives the server at. */'),
		('/** The identity the fixture server answers `initialize` with. */',
		 '/** Supplies the identity the fixture server answers `initialize` with. */'),
		("/** One `✓ <scenario>: N passed, M failed` line in the runner's summary block. */",
		 "/** Matches one `✓ <scenario>: N passed, M failed` line in the runner's summary block. */"),
		("/** The runner's closing `Total: N passed, M failed` line. */",
		 "/** Matches the runner's closing `Total: N passed, M failed` line. */"),
		("/** The scenario-name prefix marking the runner's OAuth family. */",
		 "/** Names the scenario-name prefix marking the runner's OAuth family. */"),
		("/** The `list` heading that opens the runner's client-scenario section. */",
		 "/** Matches the `list` heading that opens the runner's client-scenario section. */"),
		('/** One `  - <scenario> [<revisions>]` entry inside a `list` section. */',
		 '/** Matches one `  - <scenario> [<revisions>]` entry inside a `list` section. */'),
		(" * Every client scenario the runner's own `list` reports as applicable at",
		 " * Lists every client scenario the runner's own `list` reports as applicable at"),
		("/** The runner's per-scenario `Passed: N/D, M failed, W warnings` result line in client mode. */",
		 "/** Matches the runner's per-scenario `Passed: N/D, M failed, W warnings` result line in client mode. */"),
		("/** One conformance scenario's tally, exactly as the runner's summary reports it. */",
		 "/** Describes one conformance scenario's tally, exactly as the runner's summary reports it. */"),
		(" * One client scenario's outcome, exactly as the runner's per-scenario result block reports it.",
		 " * Describes one client scenario's outcome, exactly as the runner's per-scenario result block reports it."),
		('/** The parsed outcome of one whole conformance run. */',
		 '/** Describes the parsed outcome of one whole conformance run. */'),
		('/** The JSON Schema spelling of an integer millisecond value in the Tasks extension. */',
		 '/** Supplies the JSON Schema spelling of an integer millisecond value in the Tasks extension. */'),
		('/** The properties every task variant shares. */', '/** Lists the properties every task variant shares. */'),
		('/** The properties every task owes. */', '/** Lists the properties every task owes. */'),
		(' * The rich content the content-block scenarios ask for VERBATIM.',
		 ' * Supplies the rich content the content-block scenarios ask for VERBATIM.'),
		(' * The JSON Schema 2020-12 document `json-schema-2020-12` reads back out of `tools/list`.',
		 ' * Supplies the JSON Schema 2020-12 document `json-schema-2020-12` reads back out of `tools/list`.'),
		(' * The text each input-driven tool answers with once its rounds are answered.',
		 ' * Supplies the text each input-driven tool answers with after its rounds are answered.'),
		(' * Build the live tool registry the conformance scenarios call.',
		 ' * Builds the live tool registry the conformance scenarios call.'),
		("/** The signing secret the fixture's continuation port protects its request state with. */",
		 "/** Supplies the signing secret the fixture's continuation port protects its request state with. */"),
		('/** The principal the fixture binds into protected state; this host authenticates nobody. */',
		 '/** Names the principal the fixture binds into protected state; this host authenticates nobody. */'),
		('/** How long one protected continuation round stays valid, in milliseconds. */',
		 '/** Bounds how long one protected continuation round stays valid, in milliseconds. */'),
		('/** The integrity-protected continuation port both the tool and prompt rounds seal state with. */',
		 '/** Supplies the integrity-protected continuation port both the tool and prompt rounds seal state with. */'),
		(' * The rounds each input-driven tool asks for, in the order the scenario drives them.',
		 ' * Lists the rounds each input-driven tool asks for, in the order the scenario drives them.'),
		(' * Decide whether the call in hand still owes this host an answer.',
		 ' * Decides whether the call in hand still owes this host an answer.'),
		(' * Project the accepted string answers a verified retry carried.',
		 ' * Projects the accepted string answers a verified retry carried.'),
		('/** The static resources the fixture advertises over `resources/list`. */',
		 '/** Lists the static resources the fixture advertises over `resources/list`. */'),
		('/** The contents each static resource URI resolves to. */',
		 '/** Maps each static resource URI to the contents it resolves to. */'),
		(" * The already-substituted form of the fixture's one resource template.",
		 " * Matches the already-substituted form of the fixture's one resource template."),
		('/** The descriptor form of {@link CONFORMANCE_TEMPLATE}, as `resources/templates/list` advertises it. */',
		 '/** Supplies the descriptor form of {@link CONFORMANCE_TEMPLATE}, as `resources/templates/list` advertises it. */'),
		(' * Resolve one already-substituted template URI to its JSON document.',
		 ' * Resolves one already-substituted template URI to its JSON document.'),
		('/** The prompts the fixture advertises over `prompts/list`. */',
		 '/** Lists the prompts the fixture advertises over `prompts/list`. */'),
		(' * The input request the multi-round prompt asks for before it can be filled.',
		 ' * Supplies the input request the multi-round prompt asks for before it can be filled.'),
		('/** The canonical state the multi-round prompt seals into its opaque `requestState`. */',
		 '/** Supplies the canonical state the multi-round prompt seals into its opaque `requestState`. */'),
		(" * Issue the multi-round prompt's round, or let a verified retry through.",
		 " * Issues the multi-round prompt's round, or lets a verified retry through."),
		(" * Fill one named prompt with the caller's arguments.",
		 " * Fills one named prompt with the caller's arguments."),
		('/** The candidate values each prompt argument completes to. */',
		 '/** Lists the candidate values each prompt argument completes to. */'),
		("/** The candidate identifiers the fixture's resource template completes to. */",
		 "/** Lists the candidate identifiers the fixture's resource template completes to. */"),
		(' * Project one candidate list onto the fragment the client has typed so far.',
		 ' * Projects one candidate list onto the fragment the client has typed so far.'),
		(' * Build the whole conformance host — every port `MCPServerOptions` publishes, backed by',
		 ' * Builds the whole conformance host — every port `MCPServerOptions` publishes, backed by'),
		(' * Start the conformance fixture on an ephemeral loopback port.',
		 ' * Starts the conformance fixture on an ephemeral loopback port.'),
		(' * Read the runner build the package manifest pins.',
		 ' * Reads the runner build the package manifest pins.'),
		(" * Resolve the installed runner's entry module.", " * Resolves the installed runner's entry module."),
		(' * Invoke the installed conformance runner and collect everything it wrote.',
		 ' * Invokes the installed conformance runner and collects everything it wrote.'),
		(" * Parse the runner's `=== SUMMARY ===` block.", " * Parses the runner's `=== SUMMARY ===` block."),
		(" * Drive the pinned runner's whole `server` scenario set at {@link CONFORMANCE_SPEC} against",
		 " * Drives the pinned runner's whole `server` scenario set at {@link CONFORMANCE_SPEC} against"),
		(' * Compose the command the runner spawns as the client under test.',
		 ' * Composes the command the runner spawns as the client under test.'),
		(" * Read every client scenario name out of the runner's own `list` output.",
		 " * Reads every client scenario name out of the runner's own `list` output."),
		(" * Parse the runner's per-scenario result block from one client-mode run.",
		 " * Parses the runner's per-scenario result block from one client-mode run."),
		(" * Drive this package's own client through every scenario in",
		 " * Drives this package's own client through every scenario in"),
	],
	'src/browser/factories.ts': [
		(" * that drives a REMOTE MCP server over the native `WebSocket` global, the browser\n"
		 " * sibling of the Node face's `createWebSocketClientTransport` (`@orkestrel/mcp/server`).",
		 " * that drives a REMOTE MCP server over the native `WebSocket` global. This factory is the\n"
		 " * browser sibling of the Node face's `createWebSocketClientTransport` (`@orkestrel/mcp/server`)."),
	],
	'src/browser/transports/WebSocketClientTransport.ts': [
		(" * Drives a REMOTE MCP server over the native `WebSocket` global from the browser face — a\n"
		 " * CLIENT {@link MCPMessageTransportInterface}, the browser sibling of the Node face's\n"
		 " * {@link import('@orkestrel/mcp/server').WebSocketClientTransport}.",
		 " * Drives a REMOTE MCP server over the native `WebSocket` global from the browser face, as a\n"
		 " * CLIENT {@link MCPMessageTransportInterface}. This class is the browser sibling of the Node\n"
		 " * face's {@link import('@orkestrel/mcp/server').WebSocketClientTransport}."),
	],
}

for path, pairs in edits.items():
	target = Path(path)
	text = target.read_text(encoding='utf8')
	for before, after in pairs:
		count = text.count(before)
		if count != 1:
			raise SystemExit(f'{path}: expected exactly one occurrence, found {count}: {before!r}')
		text = text.replace(before, after)
	target.write_text(text, encoding='utf8')
	print(f'{path} edited')
