from pathlib import Path

EDITS = {
 'tests/setup.ts': [
  (" * One turn a {@link createScriptedProvider} replays — either a bare {@link ProviderResult}",
   " * Replays one turn of a {@link createScriptedProvider} script — either a bare {@link ProviderResult}"),
  (" * One recorded `generate` / `stream` call on a {@link createScriptedProvider} (when `record`).",
   " * Describes one recorded `generate` / `stream` call on a {@link createScriptedProvider} (when `record`)."),
  ("/** How a {@link createScriptedProvider} chunks a turn's content into stream deltas. */",
   "/** Chunks a turn's content into the stream deltas a {@link createScriptedProvider} emits. */"),
  (" * - `delay` — ms paused at the start of each call (lets a test observe concurrency via\n",
   " * - `delay` — ms paused at the start of each call (lets a test observe concurrency through\n"),
  (" * A scripted {@link ProviderInterface} plus its live recorders — `maxInFlight` is the\n * high-water mark of concurrent calls (so a test can prove a queue / runner bounded the\n * agent jobs, e.g. `concurrency: 2` ⇒ `maxInFlight <= 2`), `started` counts calls, and",
   " * Extends a scripted {@link ProviderInterface} with its live recorders — `maxInFlight` is the\n * high-water mark of concurrent calls (so a test can prove a queue / runner bounded the\n * agent jobs, for example `concurrency: 2` ⇒ `maxInFlight <= 2`), `started` counts calls, and"),
  (" * Normalize a {@link ScriptedTurn} to its `{ result, deltas, thoughts }` parts",
   " * Normalizes a {@link ScriptedTurn} to its `{ result, deltas, thoughts }` parts"),
  (" * Chunk a turn's whole content into ONE stream delta",
   " * Chunks a turn's whole content into ONE stream delta"),
  (" * Create the shared scripted {@link ProviderInterface} for deterministic, Ollama-free agent",
   " * Creates the shared scripted {@link ProviderInterface} for deterministic, Ollama-free agent"),
  (" * The scripted {@link ProviderInterface} {@link createScriptedProvider} builds — a REAL provider\n * that replays its turns, honours its signal between every delta, and records its calls.",
   " * Replays the turns {@link createScriptedProvider} scripts — a REAL {@link ProviderInterface}\n * that honours its signal between every delta and records its calls."),
  (" * Build a {@link ToolCall} for an agent / loop test",
   " * Builds a {@link ToolCall} for an agent / loop test"),
  (" * Build a {@link TokenUsage} for an agent / budget test",
   " * Builds a {@link TokenUsage} for an agent / budget test"),
  (" * The canonical `add` tool — a REAL {@link ToolInterface} that returns a fixed `5`, the",
   " * Builds the canonical `add` tool — a REAL {@link ToolInterface} that returns a fixed `5`, the"),
  (" * The canonical `loop` tool — a REAL {@link ToolInterface} that always returns `'again'`,",
   " * Builds the canonical `loop` tool — a REAL {@link ToolInterface} that always returns `'again'`,"),
  (" * Build an {@link AgentJobInput} for an agent-job test",
   " * Builds an {@link AgentJobInput} for an agent-job test"),
  (" * Create a deterministic stub {@link ConversationSummaryHandler} for the conversation-layer tests",
   " * Creates a deterministic stub {@link ConversationSummaryHandler} for the conversation-layer tests"),
  ("/** A {@link SchedulerInterface} that records how many turn boundaries its `yield` paced. */",
   "/** Records how many turn boundaries a {@link SchedulerInterface}'s `yield` paced. */"),
  (" * Create a {@link RecordingSchedulerInterface} — a real `SchedulerInterface` whose",
   " * Creates a {@link RecordingSchedulerInterface} — a real `SchedulerInterface` whose"),
  (" * Build a REAL {@link ConversationSnapshot} the way a conversation produces one",
   " * Builds a REAL {@link ConversationSnapshot} the way a conversation produces one"),
  ("/** The literal values a {@link conversationStoreRoundTrip} result must carry, shared by every twin. */",
   "/** Names the literal values a {@link conversationStoreRoundTrip} result must carry, shared by every twin. */"),
  (" * The literal values `buildConversationSnapshot()`'s round trip must reproduce",
   " * Holds the literal values `buildConversationSnapshot()`'s round trip must reproduce"),
  (" * Run the round-trip scenario of the shared `ConversationStoreInterface` contract",
   " * Runs the round-trip scenario of the shared `ConversationStoreInterface` contract"),
  (" * Run the upsert scenario:", " * Runs the upsert scenario:"),
  (" * Run the delete scenario:", " * Runs the delete scenario:"),
  (" * Run the absent-delete scenario:", " * Runs the absent-delete scenario:"),
  (" * Run the absent-get scenario:", " * Runs the absent-get scenario:"),
  (" * Run the two-ids-coexist scenario:", " * Runs the two-ids-coexist scenario:"),
  (" * Build a {@link ToolManagerInterface} pre-seeded with working tools",
   " * Builds a {@link ToolManagerInterface} pre-seeded with working tools"),
  (" * Build an {@link AgentContextInterface} whose ACTIVE workspace holds two TEXT files",
   " * Builds an {@link AgentContextInterface} whose ACTIVE workspace holds two TEXT files"),
  (" * Build an {@link AgentContextInterface} carrying a system prompt, two named instructions",
   " * Builds an {@link AgentContextInterface} carrying a system prompt, two named instructions"),
  (" * Resolve the instructions section's `open` (its header) at whichever cascade levels the",
   " * Resolves the instructions section's `open` (its header) at whichever cascade levels the"),
  (" * Resolve ONE instruction item's rendering at whichever cascade levels the arguments set",
   " * Resolves ONE instruction item's rendering at whichever cascade levels the arguments set"),
  (" * Register a conversation on a {@link ConversationManagerInterface} and compact it, so the",
   " * Registers a conversation on a {@link ConversationManagerInterface} and compacts it, so the"),
 ],
 'tests/src/core/AgentRegistry.test.ts': [
  ("a partial — proving the threaded signal is the agent's actual cancel, not just a\n\t\t// pre-aborted short-circuit.",
   "a partial — proving the threaded signal is the agent's actual cancel, not a\n\t\t// pre-aborted short-circuit."),
 ],
 'tests/src/core/conversations/Conversation.test.ts': [
  ("// view() is now just the single section's FRAMED recap message",
   "// view() is now the single section's FRAMED recap message"),
  ("// The RAW baseline: what view() would estimate with UNFRAMED section summaries (just the\n\t\t// summary text), versus the ACTUAL framed view().",
   "// The RAW baseline: what view() would estimate with UNFRAMED section summaries (the\n\t\t// summary text alone), versus the ACTUAL framed view()."),
  ("// its original message must still be found via search.",
   "// its original message must still be found through search."),
 ],
 'tests/src/core/AgentContext.test.ts': [
  ("// description, or definition; tools reach the provider via definitions(), not here.",
   "// description, or definition; tools reach the provider through definitions(), not here."),
  ("// Identical to the original lean behavior: just [system, user].",
   "// Identical to the original lean behavior: [system, user] and nothing else."),
  ("// One active workspace holding BOTH a text file (added via write) and an image file (seeded,",
   "// One active workspace holding BOTH a text file (added through write) and an image file (seeded,"),
  ("// 'a' renders via its per-item override; 'b' via the built-in content — same section.",
   "// 'a' renders through its per-item override; 'b' through the built-in content — same section."),
  ("// authoritative). A manager is supplied via AgentContextOptions.conversations;",
   "// authoritative). A manager is supplied through AgentContextOptions.conversations;"),
 ],
 'tests/src/core/integration.test.ts': [
  ("// The shared scripted provider (used across the agent-job tests) is ALSO just a\n\t\t// ProviderInterface",
   "// The shared scripted provider (used across the agent-job tests) is ALSO a\n\t\t// ProviderInterface"),
 ],
 'tests/src/core/factories.test.ts': [
  ("// off `AgentResult.partial` alone, not off the budget-via-loop-tool mechanism in",
   "// off `AgentResult.partial` alone, not off the loop-tool budget mechanism in"),
  ("// Beyond the budget-via-loop-tool route already covered above: a SECOND independent",
   "// Beyond the loop-tool budget route already covered above: a SECOND independent"),
  ("// handler fans the child out via `void controller.spawn(...)` and RETURNS (never",
   "// handler fans the child out through `void controller.spawn(...)` and RETURNS (never"),
 ],
 'tests/src/core/helpers.test.ts': [
  ("// finish resolves with the run's result; a PARTIAL (forced via a pre-aborted signal,",
   "// finish resolves with the run's result; a PARTIAL (forced through a pre-aborted signal,"),
 ],
 'tests/src/core/Agent.test.ts': [
  ("// test opts the provider into `record: true` (to assert, via `provider.calls`, the",
   "// test opts the provider into `record: true` (to assert, through `provider.calls`, the"),
  ("// messages / tools each call saw (asserted via `provider.calls`) and treats over-running the",
   "// messages / tools each call saw (asserted through `provider.calls`) and treats over-running the"),
  ("// repeat — so a loop that should have stopped (a cap / budget / cancel) but didn't is caught.",
   "// repeat — so a loop that had to stop (a cap / budget / cancel) but didn't is caught."),
  ("// Tools reach the provider via definitions(), never serialized into messages.",
   "// Tools reach the provider through definitions(), never serialized into messages."),
  ("// Pull exactly ONE chunk via the iterator protocol, then `return()` the iterator —",
   "// Pull exactly ONE chunk through the iterator protocol, then `return()` the iterator —"),
  ("// error via the bound signal's `aborted` flag (see the loop's `#provide` catch), so the",
   "// error through the bound signal's `aborted` flag (see the loop's `#provide` catch), so the"),
  ("// Pass listeners via the reserved `on` option — they must fire without a later .on().",
   "// Pass listeners through the reserved `on` option — they must fire without a later .on()."),
  ("// Each \"request\" makes the thread `id` active (creating via `add({ id })` when absent, then",
   "// Each \"request\" makes the thread `id` active (creating through `add({ id })` when absent, then"),
  ("// path and exits via the `for` condition (never a `break`) -- the same shape as a genuine",
   "// path and exits through the `for` condition (never a `break`) -- the same shape as a genuine"),
 ],
}

for path, pairs in EDITS.items():
    p = Path(path)
    text = p.read_text()
    for old, new in pairs:
        c = text.count(old)
        if c != 1:
            raise SystemExit(f'NOT FOUND VERBATIM (or ambiguous) in {path}: occurrences={c} :: {old[:80]!r}')
        text = text.replace(old, new)
    p.write_text(text)
    print(f'{path}: {len(pairs)} edits applied')
