export const meta = {
  name: 'sortable-round',
  description: 'Audit the veneer sortable (drags/) against the elements drag factory, the W3C and APG material, and the platform; read the Sass surface the styles layer can draw from the Bootstrap partials; judge and write the improvement verdict with its units',
  phases: [{ title: 'Read', detail: 'four readers: the veneer module, the elements drag, the platform and APG material, the Sass surface' }, { title: 'Check', detail: 'one refuter per reading' }, { title: 'Judge', detail: 'one judge over the four verified readings' }, { title: 'Write', detail: 'one writer lands the verdict' }],
}
const READING = {
  type: 'object',
  properties: {
    subject: { type: 'string' },
    files: { type: 'array', items: { type: 'string' } },
    facts: { type: 'array', items: { type: 'object', properties: { topic: { type: 'string' }, fact: { type: 'string' }, citation: { type: 'string' } }, required: ['topic', 'fact', 'citation'] } },
    gaps: { type: 'array', items: { type: 'object', properties: { gap: { type: 'string' }, citation: { type: 'string' } }, required: ['gap', 'citation'] } },
    questions: { type: 'array', items: { type: 'string' } },
  },
  required: ['subject', 'files', 'facts', 'gaps', 'questions'],
}
const VERDICT = {
  type: 'object',
  properties: { subject: { type: 'string' }, upheld: { type: 'number' }, corrected: { type: 'array', items: { type: 'object', properties: { claim: { type: 'string' }, correction: { type: 'string' }, evidence: { type: 'string' } }, required: ['claim', 'correction', 'evidence'] } }, missing: { type: 'array', items: { type: 'string' } } },
  required: ['subject', 'upheld', 'corrected', 'missing'],
}
const JUDGMENT = {
  type: 'object',
  properties: {
    findings: { type: 'array', items: { type: 'object', properties: { finding: { type: 'string' }, severity: { type: 'string' }, evidence: { type: 'string' }, source: { type: 'string' } }, required: ['finding', 'severity', 'evidence', 'source'] } },
    units: { type: 'array', items: { type: 'object', properties: { id: { type: 'string' }, title: { type: 'string' }, owned: { type: 'array', items: { type: 'string' } }, contract: { type: 'array', items: { type: 'string' } }, proofs: { type: 'array', items: { type: 'string' } }, styles: { type: 'string' }, engine: { type: 'string' }, order: { type: 'number' } }, required: ['id', 'title', 'owned', 'contract', 'proofs', 'styles', 'engine', 'order'] } },
    sass_doctrine: { type: 'array', items: { type: 'object', properties: { rule: { type: 'string' }, mechanism: { type: 'string' }, home: { type: 'string' } }, required: ['rule', 'mechanism', 'home'] } },
    rejected: { type: 'array', items: { type: 'object', properties: { lesson: { type: 'string' }, why: { type: 'string' } }, required: ['lesson', 'why'] } },
    questions: { type: 'array', items: { type: 'string' } },
  },
  required: ['findings', 'units', 'sass_doctrine', 'rejected', 'questions'],
}
const V = '/home/user/veneer', E = '/home/user/mikesaintsg/elements', S = '/home/user/.wave/scaffold-main-wt/.orkestrel/veneer'
const LAWS = `The veneer laws govern (${V}/AGENTS.md: single-word entity APIs, types first, derive state, no superfluous wrappers, no polling, functional core and imperative shell; ${V}/.claude/rules/browser.md and styles.md). The user's rulings (${S}/stage-b/user-rulings-2026-10-06.md § Fourth, Eighth, Eleventh, and Thirteenth rounds): the native track builds from scratch what Bootstrap lacks, the Bootstrap layer and the Bootstrap families of the engine are sealed, every veneer style lives in the styles layer as Sass over the Bootstrap partials, and the elements repository is guidance, never copied.`
const SUBJECTS = [
  { key: 'veneer-drags', type: 'distiller', prompt: `Read-only distillation of the veneer sortable as it stands. Read every file under ${V}/src/browser/drags/ and ${V}/tests/src/browser/drags/, the guide section "### Sortable list" of ${V}/guides/veneer.md (from its heading to the next "###"), the showcase specimen ${V}/app/browser/sections/sortable-list.html and the sortable rows of ${V}/app/browser/constants.ts, the sortable journey case in ${V}/tests/app/browser/integration.test.ts (Grep for sortable), the Drag 1 records under ${S} (Glob for drag* under ${S}/**; read the brief, the report, and any review), and the catalog rows that name Drag 2 or cross-list transfer in ${S}/native/catalog-2026-10-07-systems.md § Deferred. Return cited facts (file:line) on: the markup contract and data attributes, the pointer model (pointer capture, thresholds, placeholders, indicators, auto-scroll), the keyboard model (keys, focus, announcements), the events and their payloads, the ARIA and live-region writes, teardown, what the proofs pin and what they do not, the recorded deviations and open items, and the styling the specimen uses (Bootstrap utilities, no shipped fence). Gaps: what a sortable of production grade would need that this one lacks, each tied to a cited absence. Never run anything; never edit.` },
  { key: 'elements-drag', type: 'distiller', prompt: `Read-only distillation of guidance. The elements repository at ${E} is a different project and API; the user names its drag work as what to look at for "what we should use and work more on" in the veneer sortable. Read ${E}/src/browser/factories/createDrag.ts, ${E}/src/browser/composables/useDrag.ts, the drag types in ${E}/src/browser/types.ts, the drag sections of ${E}/src/browser/{constants,helpers,events,patterns}.ts it imports, ${E}/src/styles/composables/_drag.scss, the drag sections of ${E}/guides/components.md, composables.md, patterns.md, and styles.md (Grep for drag), the tests ${E}/tests/src/browser/factories/createDrag.test.ts and ${E}/tests/app/browser/pages/UseDragDropPage.test.ts, and the page they drive (Glob under ${E}/app for Drag). Return cited facts (file:line): the input model (pointer, touch, keyboard, HTML drag-and-drop or none), the state machine and thresholds, cross-container transfer, placeholders and indicators, auto-scroll, constraints (axis, handles, disabled items, groups), the events and payloads, the accessibility writes (roles, aria attributes, live announcements, focus), the styles the composable ships and how they derive from tokens, teardown, and what the tests pin. Gaps: what the elements drag leaves out that the W3C or APG material asks for. Describe, never copy code; never run; never edit.` },
  { key: 'platform', type: 'researcher', prompt: `Read-only research for a veneer sortable list (drag and drop reordering of Bootstrap list items by pointer and keyboard, with cross-list transfer as a later unit). Primary sources first: the W3C and APG material in the elements corpus at ${E}/guides/w3c/ (Grep for drag, drop, sortable, reorder, grabbed, moveBefore, pointer capture, live region), then the specifications on the web: the HTML drag and drop model and its limits for touch and accessibility, Pointer Events (pointer capture, touch-action, pointercancel), the DOM moveBefore() method and its state preservation (Chromium 133 and later), the ARIA Authoring Practices for reordering (aria-grabbed and aria-dropeffect deprecated in ARIA 1.1, the recommended live-region and keyboard patterns, the "listbox with rearrangeable options" example), the Chromium 141 and 153 status of each API, and prefers-reduced-motion for drag animation. Return cited facts (URL or file:line and the fetch date 2026-10-08) and the gaps a production sortable must close; never speculate.` },
  { key: 'sass-surface', type: 'distiller', prompt: `Read-only distillation of the Sass surface the veneer styles layer can draw from the Bootstrap partials. Read ${V}/src/bootstrap/index.scss, _tokens.scss, _mixins.scss, _utilities.scss, the folders components/ and elements/ (list every partial and the maps, variables, functions, and mixins each defines or forwards; cite the lines of the maps such as theme colors, grid breakpoints, spacers, font sizes, border radii, shadows, and the utilities map), then the styles layer ${V}/src/styles/ (every file: index.scss, _tokens.scss, _mixins.scss, _reset.scss, the elements, components, surfaces, composables, modifiers, and utilities index partials, themes/, sheet.ts, index.ts), the layer order in ${V}/tests/fixtures/styles/bootstrap.scss line 1 and ${V}/tests/setupStyles.ts (LAYER_ORDER), the guide sections of ${V}/guides/veneer.md that document the styles layer and the sheet (Grep for "## Styles", "layer", "@use"), and ${V}/.claude/rules/styles.md. Return cited facts: how a styles-layer partial can @use the Bootstrap partials (the module paths, the namespace, whether the partials are configurable through @use with), which maps and mixins exist for generating variants (per theme color, per breakpoint, per spacer), how the cascade layers are declared and which layer a veneer component lands in, how the sheet is built and tested (the digest gate, the layer proofs), and what the styles layer holds today. Gaps: what a first veneer component in the styles layer needs that the surface lacks (a forwarding partial, a variant mixin, a test fixture). Never run anything; never edit.` },
]
phase('Read')
const checked = await pipeline(
  SUBJECTS,
  (s) => agent(s.prompt, { label: `read:${s.key}`, phase: 'Read', schema: READING, model: 'opus', effort: 'high', agentType: s.type }),
  (reading, s) => agent(`Refute this reading (subject ${s.key}); open every cited file and line (or URL) and uphold, correct with the exact text, or mark the citation missing; list the omissions a judge designing the veneer sortable and its styles-layer component would need. Reading (JSON): ${JSON.stringify(reading)}. Read-only.`, { label: `refute:${s.key}`, phase: 'Check', schema: VERDICT, model: 'opus', effort: 'high', agentType: 'reviewer' }).then((verdict) => ({ key: s.key, reading, verdict })),
)
const results = checked.filter(Boolean)
phase('Judge')
const judgment = await agent(`You judge the improvement round for the veneer sortable (src/browser/drags/, "a great first try that needs a lot of improvement" in the user's words) and set the Sass doctrine for the styles layer. ${LAWS} Inputs (JSON follows): four verified readings: the veneer module, the elements drag factory as guidance, the platform and APG material, and the Sass surface. Return: findings (what the module lacks or does wrong, each with severity defect, gap, or improvement, the evidence, and the source reading), units (Drag 2 and after, each with an id, title, owned files under src/browser/drags/ or src/styles/, a contract of single-word API additions and behaviors, the proofs under Chromium 141 and 153, the styles-layer component it needs in Sass over the Bootstrap partials' maps and mixins (variants generated from the maps, never by hand), the engine astra or opus, and an order), sass_doctrine (the rules for every veneer style in the styles layer: how a partial reaches the Bootstrap partials, how variants derive from maps, which layer a component or composable lands in, how the digest gate and the layer proofs read it, where each rule is written: the veneer guide, the roadmap, or the scaffold plan's rule file), rejected (lessons from elements, the platform, or APG that do not transfer, with why: HTML drag-and-drop over pointer events, aria-grabbed, a wrapper the laws forbid), and questions for the user only where a ruling is needed. Keep the Bootstrap layer sealed; keep the elements repository as guidance; cite the reading item behind every entry. Readings: ${JSON.stringify(results)}`, { label: 'judge', phase: 'Judge', schema: JUDGMENT, model: 'opus', effort: 'high', agentType: 'planner' })
phase('Write')
const path = `${S}/native/drag-2026-10-08/verdict.md`
const written = await agent(`Write the verdict file ${path} (create the folder) from this judgment and the four verified readings. ${LAWS} Shape: a title; one opening paragraph with the user's order of 2026-10-08 and the sources read; "## Findings" as a table (finding, severity, evidence, source); "## Units" with one "### D2.n: title" per unit in order (engine, owned files, contract as a list, proofs as a list, the styles-layer component as a paragraph naming the Bootstrap maps and mixins it derives from); "## Sass doctrine for the styles layer" as a list of rules with their mechanism and home; "## Rejected" as a table; "## Questions for the user" as a numbered list with one recommendation each; "## Sources" listing the files and URLs read with the fetch date. Follow ${V}/.claude/rules/writing.md (must, can, imperative; no should, no simply, no currently or now, no above or below; introduce every list and table with a sentence; code tokens in backticks). Write only that file. Return its path and a count of findings and units. Judgment: ${JSON.stringify(judgment)}. Readings: ${JSON.stringify(results.map((r) => ({ key: r.key, facts: r.reading.facts, gaps: r.reading.gaps, corrections: r.verdict.corrected, missing: r.verdict.missing })))}`, { label: 'write', phase: 'Write', schema: { type: 'object', properties: { path: { type: 'string' }, findings: { type: 'number' }, units: { type: 'number' } }, required: ['path', 'findings', 'units'] }, model: 'opus', effort: 'high', agentType: 'opus' })
return { written, judgment, results }