import io
E=[
('src/core/inferers.ts',
 " * The era is read from the two era guards rather than restated here, so a revision added\n * to {@link SUPPORTED_MODERN_PROTOCOL_VERSIONS} or {@link SUPPORTED_LEGACY_PROTOCOL_VERSIONS}\n * carries its era with it and no third list can disagree with those two.",
 " * The era is read from the era guards rather than restated here, so a revision added\n * to {@link SUPPORTED_MODERN_PROTOCOL_VERSIONS} or {@link SUPPORTED_LEGACY_PROTOCOL_VERSIONS}\n * carries its era with it and no further list can disagree with them."),
('src/core/inferers.ts',
 " * revision has not been read and cannot answer `undefined` — every invocation took one of the\n * two published wire shapes.",
 " * revision has not been read and cannot answer `undefined` — every invocation took one of the\n * published wire shapes."),
('src/core/types.ts',
 " * {@link MCPContent} also admits, plus the two tool blocks a tool-using model produces.",
 " * {@link MCPContent} also admits, plus the tool blocks a tool-using model produces."),
('src/core/types.ts',
 " * A consumer composes any of the three arms into an {@link MCPInputRound}, and this server",
 " * A consumer composes any of the arms into an {@link MCPInputRound}, and this server"),
('src/core/types.ts',
 " * Two interfaces over one entity because two parties hold it and they are owed different\n * powers.",
 " * A second interface over one entity because the executor and the owner hold it and they are\n * owed different powers."),
('src/core/types.ts',
 " * the member. That fact is derived from the two configured options at the moment the",
 " * the member. That fact is derived from the configured options at the moment the"),
('src/core/helpers.ts',
 " * The two failures report differently on purpose.",
 " * The failures report differently on purpose."),
('src/core/helpers.ts',
 " * `properties` chain reaches. Comparing the two answers is how",
 " * `properties` chain reaches. Comparing the answers is how"),
('src/core/helpers.ts',
 " * here would be a second correlation table for ids the client is already correlating, and two\n * tables for one fact drift.",
 " * here would be a second correlation table for ids the client is already correlating, and a\n * pair of tables for one fact drift."),
('src/core/parsers.ts',
 " *   serializer under the same `limits` — so the two cannot disagree about the bound.",
 " *   serializer under the same `limits` — so they cannot disagree about the bound."),
('src/core/constants.ts',
 " * them, so the two directions cannot drift apart.",
 " * them, so the directions cannot drift apart."),
('src/core/validators.ts',
 " * names four values and permits any other a provider reports.",
 " * names `endTurn`, `stopSequence`, `maxTokens`, and `toolUse` and permits any other a provider\n * reports."),
('src/server/factories.ts',
 " * same two contracts the other way.",
 " * same contracts the other way."),
('src/server/types.ts',
 " * validation, and keepalive — live on {@link MCPSessionMiddlewareOptions}. The two `ttl`\n * values measure different things, which is why they sit on different types.",
 " * validation, and keepalive — live on {@link MCPSessionMiddlewareOptions}. This type's `ttl`\n * and that one's measure different things, which is why they sit on different types."),
]
for p,old,new in E:
    s=io.open(p,encoding='utf8').read()
    assert s.count(old)==1, (p, old[:60], s.count(old))
    io.open(p,'w',encoding='utf8').write(s.replace(old,new,1))
print('ok')
