import sys
sys.path.insert(0, '/home/user/fleet/terminal/tmp/d7n-terminal-converge')
from setdesc import set_description as sd

H = 'src/core/helpers.ts'
sd(H, 'parseKey', "Decodes one keypress's bytes into a {@link KeyEvent} — total, never throws. A `Uint8Array` is read as UTF-8; the resulting string is matched against the known control bytes and the CRLF pair ({@link CONTROL_NAMES}) and escape sequences ({@link SEQUENCE_NAMES}), falling back to a single printable character. An unrecognized sequence carries no `name`, with the raw `sequence` preserved.")
sd(H, 'isPrintable', "Checks whether a single character is printable — the fallback test {@link parseKey} applies after the control bytes and the escape sequences, so the C0 controls and DEL are excluded.")
sd(H, 'renderErrorLine', "Renders the styled failure line (`✖ message`) a form driver writes for each refused field before it asks that field again.")
sd(H, 'createInputState', "Builds the initial text-field reducer state — the sanitized label, the declared default, the styler, and the resolved theme.")
sd(H, 'renderInputView', "Renders a text-field reducer state as a styled view — the header, the pointer, and the typed value, or the default shown as a hint while nothing is typed.")
sd(H, 'createPasswordState', "Builds the initial password-field reducer state — the text-field state, plus the mask glyph each typed character renders as.")
sd(H, 'renderPasswordView', "Renders a password-field reducer state as a styled view, with the value replaced by the mask repeated so the secret is never echoed.")
sd(H, 'createConfirmState', "Builds the initial confirm-field reducer state — the sanitized label and the declared default answer.")
sd(H, 'renderConfirmView', "Renders a confirm-field reducer state as a styled view — the header and the yes/no group, with the default letter capitalized and painted by the `selected` role.")
sd(H, 'createSelectState', "Builds the initial select-field reducer state — the offered choices, with the focus pre-placed on the declared default.")
sd(H, 'renderSelectView', "Renders a select-field reducer state as a multi-line styled view — one row per choice, with the focused row marked and its help shown.")
sd(H, 'reduceSelect', "Advances a select prompt by one {@link KeyEvent} — the pure `(state, key) → PromptStep<string>` reducer. `up` / `down` (and `k` / `j`) move the focus, wrapping at the ends; return submits the focused choice's `value`; ctrl-c cancels. An empty choice list can never submit (a higher layer guards against it); any other key is ignored.")
sd(H, 'createCheckboxState', "Builds the initial checkbox-field reducer state — the offered choices, with every value in the field's `default` list pre-checked.")
sd(H, 'renderCheckboxView', "Renders a checkbox-field reducer state as a multi-line styled view — one box per choice, and the selected count beneath them.")
sd(H, 'toggleIndex', "Toggles `index` in a readonly index list — copy-on-write, returning the new sorted-by-insertion list; the primitive {@link reduceCheckbox} calls.")
sd(H, 'createEditorState', "Builds the initial editor-field reducer state — the committed lines empty, and the declared default held for a finish with nothing typed.")
sd(H, 'renderEditorView', "Renders an editor-field reducer state as a multi-line styled view — the finish hint, the committed lines, and the line in progress.")
sd(H, 'reduceEditor', "Advances an editor prompt by one {@link KeyEvent} — the pure `(state, key) → PromptStep<string>` reducer. Printable characters extend the current line; backspace shrinks it; return commits the current line and starts a fresh one; ctrl-d finishes, joining every line and falling back to the default when empty; ctrl-c cancels. The form validates the candidate after the driver fills it.")
sd(H, 'editLine', "Applies a single line-editing {@link KeyEvent} to a text buffer — the editing shared by input, password, and editor. A printable key appends its character; `backspace` drops the last character; `space` appends a space; ctrl-u clears the line; a key that edits nothing returns `undefined`.")
sd(H, 'sanitizeSchema', "Sanitizes every terminal-readable string in a parsed form schema, keeping every identity and answer string verbatim and dropping field metadata.")
sd(H, 'isInsecureRemote', "Checks whether `url` is an insecure remote endpoint — a plain `http://` URL whose host is not a loopback address. Pure string parsing (no `URL` global), so it stays total on malformed input; the {@link import('./PromptClient.js').PromptClient} warns once when a `token` would cross such an endpoint in cleartext.")
sd(H, 'serializePending', "Serializes a parked {@link PendingForm} into a `pending` {@link WireEvent}, whose frame `id` is the form's own id.")
sd(H, 'serializeExpire', "Serializes a parked form's expiry or release into an `expire` {@link WireEvent}, whose `data` is the JSON `{ id }` payload.")
sd(H, 'serializeDestroy', "Serializes the `destroy` {@link WireEvent} a broker or manager sends when it is going away, which carries no payload.")

F = 'src/core/factories.ts'
sd(F, 'createPromptClient', "Creates the SSE prompt {@link PromptClientInterface} bridge — it connects to a remote broker's SSE endpoint, dispatches each received form to a local {@link import('./types.js').TerminalInterface}, and POSTs the answer back. Universal — `fetch` and SSE are web standards.")
sd(F, 'createTerminalManager', "Creates the multi-endpoint {@link TerminalManager} — a named registry of {@link PromptInterface} brokers so several parties can `ask` forms of each other by name, with a transitive cycle check that refuses `DEADLOCK` across every in-flight ask.")
sd(F, 'createDatabaseTerminalStore', "Creates a {@link TerminalStoreInterface} backed by one table of the `databases` layer — the driver-pluggable twin of {@link createMemoryTerminalStore}, storing each endpoint's config snapshot as one opaque JSON column. The default driver is an in-memory `@orkestrel/database` driver.")

V = 'src/core/validators.ts'
sd(V, 'isPendingForm', "Narrows an unknown wire value to a {@link PendingForm} envelope — the envelope alone, because the form package's `parseForm` owns the schema payload.")
sd(V, 'isWireEvent', "Narrows an unknown value to a transport-neutral {@link WireEvent} — the guard a consumer's own transport applies to an inbound frame.")
sd(V, 'isTerminalSnapshot', "Narrows an unknown value to a {@link TerminalSnapshot} — a non-empty `id` and an optional numeric `timeout`, the read boundary a store applies to an untrusted persisted row.")

E = 'src/core/errors.ts'
sd(E, 'isTerminalError', "Narrows an unknown caught value to a {@link TerminalError}, so a caller can branch on its `code`.")

sd('src/core/Prompt.ts', 'Prompt', "Implements the headless form broker. It parks live forms, exposes their serialized schemas, applies remote answers to the authoritative form, and abandons a parked form on timeout, release, or teardown.")
sd('src/core/PromptClient.ts', 'PromptClient', "Implements the SSE form bridge. It ingests serialized forms from a remote broker without waiting on a render, drives one form at a time through a local terminal, posts each answer back, and asks again when the authoritative form refuses one.")
sd('src/core/TerminalManager.ts', 'TerminalManager', "Registers named {@link PromptInterface} brokers, one per endpoint, so several parties can `ask` forms of each other by name with a `from` → `to` attribution edge on every parked form, and refuses `DEADLOCK` on a transitive cycle across every in-flight ask.")
sd('src/core/stores/MemoryTerminalStore.ts', 'MemoryTerminalStore', "Implements the in-memory {@link TerminalStoreInterface} — a process-lifetime `Map` of {@link TerminalSnapshot} records keyed by endpoint id, the default store {@link import('../factories.js').createMemoryTerminalStore} builds and the exact twin of {@link import('./DatabaseTerminalStore.js').DatabaseTerminalStore}. It carries no idle expiry and no eviction.")
sd('src/core/stores/DatabaseTerminalStore.ts', 'DatabaseTerminalStore', "Implements a {@link TerminalStoreInterface} backed by one table of the `databases` layer — an endpoint's durable config state is a row, so persistence reduces to keyed point-access (`get` / `set` / `delete`) over a {@link TableInterface}, the driver-pluggable twin of the plain-`Map` {@link import('./MemoryTerminalStore.js').MemoryTerminalStore}. A stored `snapshot` is narrowed with {@link import('../validators.js').isTerminalSnapshot} on read.")

SH = 'src/server/helpers.ts'
sd(SH, 'isInputStream', "Checks whether `value` is a usable {@link InputStreamInterface} — a record with callable `on` / `off` `'data'` subscription methods. A total type guard: it never throws and returns `false` for anything off-shape, so it narrows the one unavoidable input boundary (the real `process.stdin`, or a fake TTY a test injects) to the exact slice the driver reads, never an assertion.")
sd(SH, 'isReadable', "Checks whether `value` is a Node {@link NodeJS.ReadableStream} — a total structural guard checking for the callable `read` / `pipe` / `on` that `node:readline`'s `createInterface` requires as its `input`. The non-TTY fallback narrows the resolved input stream through this before handing it to readline, never through an assertion, so a real piped `process.stdin` (or a `PassThrough` a test injects) crosses into the readline boundary honestly. Never throws; returns `false` for a minimal fake that isn't a full readable.")
sd(SH, 'supportsRawMode', "Checks whether an input stream can be driven in raw mode — it reports `isTTY === true` and exposes a callable `setRawMode`. The {@link import('./Terminal.js').Terminal} probes this to choose its path: true selects the interactive raw-mode fields, with arrow-key navigation and a live re-render; false selects the `node:readline` line-input fallback, because a piped or non-terminal stream cannot enter raw mode. Total — never throws.")
sd(SH, 'lineCount', "Counts the terminal lines a rendered prompt `view` occupies — one more than its newline count, so a view with no newline is a single line and a view with N newlines spans N+1 lines. The basis of the in-place re-render: the driver records the line count of the view it wrote so the next redraw knows how far up to move the cursor before overwriting. Total; an empty string is one empty line.")
sd(SH, 'renderCursorUp', "Returns the cursor-up control sequence that moves the cursor up `count` lines (`ESC[{count}A`), or the empty string when `count` is zero or negative, because no movement is needed and `ESC[0A` is a wasted write. The pure step the in-place re-render uses to climb back over the previous view before clearing it. Total.")
sd(SH, 'redrawPrefix', "Returns the full reposition-and-clear prefix to write before re-rendering a prompt view in place — given the line count of the previous view, it moves the cursor up over those lines, returns it to column 0, and erases everything from there to the end of the screen, so the next view is drawn on a clean region and a taller previous view leaves no orphaned rows. Pure; the driver writes this immediately followed by the new view.")
sd(SH, 'fieldToText', "Projects any field the walk reads as a line of text into the {@link TextField} the text reducer takes — `text` itself, and the controls a terminal has no widget for: `number`, `date`, `time`, `datetime`, `color`, and one `file` entry. The label carries that control's format cue from {@link CONTROL_HINTS}, and a declared `default` becomes the line a bare return submits. The projection carries no rule, because the authoritative form still evaluates the answer this line binds; it exists only so one reducer covers every one of them.")
sd(SH, 'filterEnabled', "Returns the choices a `select` or `checkbox` field actually offers — the form refuses a disabled choice's value at every door, including a fill, so the walk never puts one in front of the cursor. Pair with {@link filterDisabled} to tell the reader what was withheld.")
sd(SH, 'filterDisabled', "Returns the choices a `select` or `checkbox` field shows but refuses — the complement of {@link filterEnabled}, rendered by {@link renderUnavailableLine} above the list so a reader sees why a declared choice is missing from it.")
sd(SH, 'renderLockedLine', "Renders the read-only line a locked field shows — its label, the {@link LOCKED_MARK}, and the answer the form already holds. The walk writes this instead of a prompt, because the field is still validated and still submitted but must not be edited here.")
sd(SH, 'renderSuggestionLine', "Renders the line listing an open select's offered values above its text prompt — a suggestion list, because an open select admits an answer the list does not offer.")

sd('src/server/factories.ts', 'createTerminal', "Creates the interactive terminal form driver — the local-keyboard arm of the terminal trio, beside the core headless `createPrompt` broker and the SSE `createPromptClient` bridge. Where the broker parks a live form until somebody elsewhere answers it, a `Terminal` answers one here: it walks the form's fields in schema order, drives each control's pure reducer over raw-mode stdin, binds every answer through the form's own `fill`, and submits. It is the only impure part of the terminal stack.")
sd('src/server/Terminal.ts', 'Terminal', "Implements {@link TerminalInterface} for a human at this machine's keyboard — the interactive form driver, and the only impure part of the terminal stack. {@link ask} walks one form's fields in schema order, feeds raw-mode stdin bytes through `parseKey` into the matching pure reducer, renders each returned view in place, binds every answer through the form's own `fill`, and re-asks what the form refused. It owns no form logic: the schema, the rules, the values, and the settlement all belong to the form it is given, and this class owns only raw mode, the cursor, and the re-render.")

C = 'src/core/constants.ts'
sd(C, 'SEQUENCE_NAMES', "Holds the exact escape sequence to canonical key name table {@link import('./helpers.js').parseKey} consults for the navigation and editing keys. Covers the CSI form (`ESC[A`…) and the SS3 form (`ESCOA`…) of the arrows, plus the `home` / `end` / `delete` CSI sequences with their numeric-tilde variants. The source of truth for the multi-byte key decode; frozen.")
sd(C, 'CONTROL_NAMES', "Holds the control byte (or CRLF pair) to key descriptor table {@link import('./helpers.js').parseKey} consults for the one-byte keys and the two-byte CRLF Enter chunk. Each entry carries the canonical `name` and whether it is a `ctrl` combination. The source of truth for that decode; frozen.")
sd(C, 'PROMPT_ICONS', "Holds the terminal-owned glyphs {@link DEFAULT_PROMPT_THEME} assembles its `icons` from, beside the console module's own success and error marks. Read only when the default theme is assembled; a view reads its resolved theme and never this constant. Frozen.")
sd(C, 'SSE_EVENTS', "Holds the SSE `event:` names the broker emits and the {@link import('./types.js').PromptClientInterface} dispatches on — `pending`, `expire`, and `destroy`. Frozen; the source of truth for the wire event vocabulary.")
sd(C, 'HEADER_TOKEN', "Names the auth-token request header the {@link import('./types.js').PromptClientInterface} sends when a `token` is configured — `x-orkestrel-token`.")
sd(C, 'ACCEPT_EVENT_STREAM', "Names the `Accept` header value that opens the broker's SSE stream — `text/event-stream`.")

SC = 'src/server/constants.ts'
sd(SC, 'CSI_UP', "Holds the cursor-up sequence template (`ESC[{count}A`) — {@link import('./helpers.js').renderCursorUp} interpolates the `{count}` placeholder with the number of lines to climb. Kept as a template so the count stays out of the constant.")
sd(SC, 'CLEAR_DOWN', "Erases from the cursor down to the end of the screen (`ESC[J`) — wipes the whole previous view, which a `select` or `checkbox` can spread over several lines, in one write before the new view is rendered, so a redraw never leaves orphaned rows behind.")
sd(SC, 'SUGGESTION_LEAD', "Holds the lead on the line listing an open `select`'s offered values, which a typed answer can ignore.")
sd(SC, 'UNAVAILABLE_LEAD', "Holds the lead on the line listing the choices a `select` or `checkbox` shows but refuses, so a reader sees why one is missing from the list it heads.")
print('rest ok')
