# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, '/home/user/scaffold/tmp/units/voice/edits')
from apply import apply

P = '/home/user/fleet/terminal/src/core/constants.ts'
pairs = [
 ("/** Carriage return (`\\r`, U+000D) — Enter on most terminals. */",
  "/** Names the carriage return byte (`\\r`, U+000D) — Enter on most terminals. */"),
 ("/** Line feed (`\\n`, U+000A) — Enter on some terminals / pasted input. */",
  "/** Names the line feed byte (`\\n`, U+000A) — Enter on some terminals / pasted input. */"),
 ("/** Tab (`\\t`, U+0009). */",
  "/** Names the tab byte (`\\t`, U+0009). */"),
 ("/** Escape (ESC, U+001B) — the lone byte, and the lead byte of every CSI / SS3 sequence. */",
  "/** Names the escape byte (ESC, U+001B) — the lone byte, and the lead byte of every CSI / SS3 sequence. */"),
 ("/** Backspace (BS, U+0008) — Ctrl+H / some terminals' Backspace. */",
  "/** Names the backspace byte (BS, U+0008) — Ctrl+H / some terminals' Backspace. */"),
 ("/** Delete (DEL, U+007F) — the usual Backspace byte on a Unix TTY. */",
  "/** Names the delete byte (DEL, U+007F) — the usual Backspace byte on a Unix TTY. */"),
 ("/** Space (U+0020). */",
  "/** Names the space byte (U+0020). */"),
 ("/** Ctrl+C (ETX, U+0003) — interrupt / cancel. */",
  "/** Names the Ctrl+C byte (ETX, U+0003) — interrupt / cancel. */"),
 ("/** Ctrl+D (EOT, U+0004) — end-of-transmission / finish (the editor's commit key). */",
  "/** Names the Ctrl+D byte (EOT, U+0004) — end-of-transmission / finish (the editor's commit key). */"),
 ("/** Ctrl+U (NAK, U+0015) — clear the current line. */",
  "/** Names the Ctrl+U byte (NAK, U+0015) — clear the current line. */"),
 ("/** Ctrl+A (SOH, U+0001) — move to start of line. */",
  "/** Names the Ctrl+A byte (SOH, U+0001) — move to start of line. */"),
 ("/** Ctrl+E (ENQ, U+0005) — move to end of line. */",
  "/** Names the Ctrl+E byte (ENQ, U+0005) — move to end of line. */"),
 (" * The Control Sequence Introducer lead (`ESC[`) for the navigation keys — the prefix of the\n",
  " * Names the Control Sequence Introducer lead (`ESC[`) for the navigation keys — the prefix of\n"),
 (" * arrow / home / end / delete sequences {@link SEQUENCE_NAMES} is keyed by. Named `KEY_CSI`\n",
  " * the arrow / home / end / delete sequences {@link SEQUENCE_NAMES} is keyed by. Named `KEY_CSI`\n"),
 ("/** The Single Shift Three lead (`ESCO`) — the alternate arrow-key prefix some terminals emit (`ESC O A`). */",
  "/** Names the Single Shift Three lead (`ESCO`) — the alternate arrow-key prefix some terminals emit (`ESC O A`). */"),
 (" * The exact escape SEQUENCE → canonical key NAME table {@link import('./helpers.js').parseKey}\n",
  " * Holds the exact escape SEQUENCE → canonical key NAME table {@link import('./helpers.js').parseKey}\n"),
 (" * The control BYTE (or CRLF pair) → key descriptor table {@link import('./helpers.js').parseKey}\n",
  " * Holds the control BYTE (or CRLF pair) → key descriptor table {@link import('./helpers.js').parseKey}\n"),
 ("/** The default mask glyph {@link import('./helpers.js').createPasswordState} uses — `*`. */",
  "/** Names the default mask glyph {@link import('./helpers.js').createPasswordState} uses — `*`. */"),
 (" * The six default glyphs {@link DEFAULT_PROMPT_THEME} assembles its `icons` from. Read only when\n",
  " * Holds the six default glyphs {@link DEFAULT_PROMPT_THEME} assembles its `icons` from. Read only when\n"),
 (" * Every {@link import('./types.js').PromptRole}, in one frozen list — the role axis's source of\n",
  " * Holds every {@link import('./types.js').PromptRole}, in one frozen list — the role axis's source\n"),
 (" * truth. {@link import('./helpers.js').createPromptTheme} walks it to merge a partial theme, and\n",
  " * of truth. {@link import('./helpers.js').createPromptTheme} walks it to merge a partial theme, and\n"),
 (" * The {@link import('./types.js').PromptTheme} every prompt renders with unless its options supply\n",
  " * Holds the {@link import('./types.js').PromptTheme} every prompt renders with unless its options supply\n"),
 ("/** How long (ms) the {@link import('./types.js').PromptInterface} broker parks an unanswered prompt before it expires — 5 minutes. */",
  "/** Sets how long (ms) the {@link import('./types.js').PromptInterface} broker parks an unanswered prompt before it expires — 5 minutes. */"),
 ("/** How long (ms) the {@link import('./types.js').PromptClientInterface} waits before each reconnect attempt — 2 seconds. */",
  "/** Sets how long (ms) the {@link import('./types.js').PromptClientInterface} waits before each reconnect attempt — 2 seconds. */"),
 (" * The SSE `event:` names the broker emits and the {@link import('./types.js').PromptClientInterface}\n",
  " * Holds the SSE `event:` names the broker emits and the {@link import('./types.js').PromptClientInterface}\n"),
 ("/** The auth-token request header the {@link import('./types.js').PromptClientInterface} sends. */",
  "/** Names the auth-token request header the {@link import('./types.js').PromptClientInterface} sends. */"),
 ("/** The `Accept` header value that opens the broker's SSE stream. */",
  "/** Names the `Accept` header value that opens the broker's SSE stream. */"),
 (" * The maximum number of characters the {@link import('./types.js').PromptClientInterface} lets its\n",
  " * Sets the maximum number of characters the {@link import('./types.js').PromptClientInterface} lets its\n"),
]
apply(P, pairs)
