# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, '/home/user/scaffold/tmp/units/voice/edits')
from apply import apply
P = '/home/user/fleet/terminal/src/core/types.ts'
def pre(old, verb, rest):
    return (" * " + old, " * " + verb + " " + rest)
pairs = [
 (" * One decoded keypress — the TTY-agnostic representation of a single key, the output of",
  " * Represents one decoded keypress — the TTY-agnostic representation of a single key, the output of"),
 (" * One glyph slot a rendered field draws — the icon axis of a {@link PromptTheme}. A named value",
  " * Names one glyph slot a rendered field draws — the icon axis of a {@link PromptTheme}. A named value"),
 (" * One styling slot a rendered field paints through — the semantic axis of a {@link PromptTheme}. A",
  " * Names one styling slot a rendered field paints through — the semantic axis of a {@link PromptTheme}. A"),
 (" * A resolved PRESENTATION — the glyph for every {@link PromptIcon} and the console {@link Style}",
  " * Represents a resolved PRESENTATION — the glyph for every {@link PromptIcon} and the console {@link Style}"),
 (" * The PARTIAL {@link PromptTheme} an option bag carries — every icon and every role is optional,",
  " * Represents the PARTIAL {@link PromptTheme} an option bag carries — every icon and every role is optional,"),
 (" * The immutable state a text field's reducer carries — built by",
  " * Represents the immutable state a text field's reducer carries — built by"),
 (" * The immutable state a password field's reducer carries — the text state with the mask glyph in",
  " * Represents the immutable state a password field's reducer carries — the text state with the mask glyph in"),
 (" * The immutable state a confirm field's reducer carries. It holds no typed value, because the",
  " * Represents the immutable state a confirm field's reducer carries. It holds no typed value, because the"),
 (" * The immutable state a select field's reducer carries.\n",
  " * Represents the immutable state a select field's reducer carries.\n"),
 (" * The immutable state a checkbox field's reducer carries — the select state plus the ticked set.",
  " * Represents the immutable state a checkbox field's reducer carries — the select state plus the ticked set."),
 (" * The immutable state an editor field's reducer carries — the committed lines and the line still",
  " * Represents the immutable state an editor field's reducer carries — the committed lines and the line still"),
 (" * Where one field's reducer stands after a key. `active`: keep asking, because the key was",
  " * Names where one field's reducer stands after a key. `active`: keep asking, because the key was"),
 (" * The result of one reducer step — the next `state`, the rendered `view`, the `status`, and, on",
  " * Represents the result of one reducer step — the next `state`, the rendered `view`, the `status`, and, on"),
 (" * The machine-readable condition carried by a {@link import('./errors.js').TerminalError} — the",
  " * Names the machine-readable condition carried by a {@link import('./errors.js').TerminalError} — the"),
 (" * The contract for asking a form of a human at a keyboard — one method, because a form is one",
  " * Declares the contract for asking a form of a human at a keyboard — one method, because a form is one"),
 (" * The lifecycle status of a parked {@link PendingForm} — where the TICKET stands, which is not",
  " * Names the lifecycle status of a parked {@link PendingForm} — where the TICKET stands, which is not"),
 (" * One form PARKED by the broker — an id-keyed, wire-safe record of a live form awaiting a remote",
  " * Represents one form PARKED by the broker — an id-keyed, wire-safe record of a live form awaiting a remote"),
 (" * One injected timer — arms a deadline `callback` to fire after `ms`, returning a",
  " * Represents one injected timer — arms a deadline `callback` to fire after `ms`, returning a"),
 (" * One parked form's runtime state inside the broker — the live form, the wire-safe record the",
  " * Represents one parked form's runtime state inside the broker — the live form, the wire-safe record the"),
 (" * The broker's event map — lean, errors `unknown`, no listener-error event.",
  " * Declares the broker's event map — lean, errors `unknown`, no listener-error event."),
 (" * Options for {@link import('./factories.js').createPrompt} and every {@link PromptInterface}\n * broker, including one a {@link TerminalManagerInterface} mounts per endpoint.",
  " * Configures {@link import('./factories.js').createPrompt} and every {@link PromptInterface}\n * broker, including one a {@link TerminalManagerInterface} mounts per endpoint."),
 (" * The parking envelope — everything the broker needs about a park that the form itself does not",
  " * Represents the parking envelope — everything the broker needs about a park that the form itself does not"),
 (" * Why {@link PromptInterface.answer} refused. Names its axis with `reason`.",
  " * Explains why {@link PromptInterface.answer} refused. Names its axis with `reason`."),
 (" * The headless form BROKER — parks a live form until somebody elsewhere answers it. The headless",
  " * Declares the headless form BROKER — parks a live form until somebody elsewhere answers it. The headless"),
 (" * A minimal `fetch` — the subset of the global `fetch` a {@link PromptClientInterface} uses: open",
  " * Represents a minimal `fetch` — the subset of the global `fetch` a {@link PromptClientInterface} uses: open"),
 (" * The request init a {@link PromptClientInterface} passes to its {@link FetchHandler} — the",
  " * Represents the request init a {@link PromptClientInterface} passes to its {@link FetchHandler} — the"),
 (" * The client's event map — lean, errors `unknown`, no listener-error event.",
  " * Declares the client's event map — lean, errors `unknown`, no listener-error event."),
 (" * Options for {@link import('./factories.js').createPromptClient} and the\n * {@link PromptClientInterface}.",
  " * Configures {@link import('./factories.js').createPromptClient} and the\n * {@link PromptClientInterface}."),
 (" * The SSE form BRIDGE — the client-side counterpart to {@link PromptInterface}. It receives",
  " * Declares the SSE form BRIDGE — the client-side counterpart to {@link PromptInterface}. It receives"),
 (" * The manager's event map — the name-attributed re-emission of every mounted broker's events, so a",
  " * Declares the manager's event map — the name-attributed re-emission of every mounted broker's events, so a"),
 (" * Options for {@link import('./factories.js').createTerminalManager} and the\n * {@link TerminalManagerInterface}.",
  " * Configures {@link import('./factories.js').createTerminalManager} and the\n * {@link TerminalManagerInterface}."),
 (" * Why a {@link TerminalManagerInterface.answer} call refused — an {@link AnswerError} from the",
  " * Explains why a {@link TerminalManagerInterface.answer} call refused — an {@link AnswerError} from the"),
 (" * The multi-endpoint terminal MANAGER — a registry of named {@link PromptInterface} brokers, one\n * per endpoint, so several parties (agents, tools, humans) can ask forms of each other BY NAME,\n",
  " * Declares a registry of named {@link PromptInterface} brokers, one per endpoint, so several\n * parties (agents, tools, humans) can ask forms of each other BY NAME,\n"),
 (" * One SSE-shaped wire frame — the `event` name, its already-stringified `data` payload, and an",
  " * Represents one SSE-shaped wire frame — the `event` name, its already-stringified `data` payload, and an"),
 (" * One endpoint's persisted CONFIG snapshot — `id` is the endpoint name and `timeout` its configured",
  " * Represents one endpoint's persisted CONFIG snapshot — `id` is the endpoint name and `timeout` its configured"),
 (" * One opaque persisted row — the shape a `TableInterface<TerminalSnapshotRow>`-backed store reads",
  " * Represents one opaque persisted row — the shape a `TableInterface<TerminalSnapshotRow>`-backed store reads"),
 (" * The point-access persistence seam for a {@link TerminalManagerInterface}'s endpoint configs.",
  " * Declares the point-access persistence seam for a {@link TerminalManagerInterface}'s endpoint configs."),
]
apply(P, pairs)
