# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, '/home/user/scaffold/tmp/units/voice/edits')
from apply import apply
apply('/home/user/fleet/terminal/src/server/types.ts', [
 (" * The minimal input-stream shape the driver reads — exactly the slice of a Node `tty.ReadStream` /",
  " * Represents the minimal input-stream shape the driver reads — exactly the slice of a Node `tty.ReadStream` /"),
 (" * The minimal output-stream shape the driver writes — exactly the slice of a Node `tty.WriteStream`",
  " * Represents the minimal output-stream shape the driver writes — exactly the slice of a Node `tty.WriteStream`"),
 (" * Options for {@link import('./factories.js').createTerminal} — every member optional, so a bare",
  " * Configures {@link import('./factories.js').createTerminal} — every member optional, so a bare"),
])
apply('/home/user/fleet/terminal/src/server/constants.ts', [
 ("/** The Escape byte (ESC, U+001B) — the lead byte of every CSI cursor-control sequence below. */",
  "/** Names the Escape byte (ESC, U+001B) — the lead byte of every CSI cursor-control sequence below. */"),
 ("/** The Control Sequence Introducer (`ESC[`) — the prefix of every cursor / erase sequence. */",
  "/** Names the Control Sequence Introducer (`ESC[`) — the prefix of every cursor / erase sequence. */"),
 (" * The cursor-UP sequence TEMPLATE (`ESC[{count}A`) — {@link import('./helpers.js').moveUp}",
  " * Holds the cursor-UP sequence TEMPLATE (`ESC[{count}A`) — {@link import('./helpers.js').moveUp}"),
 (" * Hide the cursor (`ESC[?25l`) — written before the driver starts redrawing a prompt so the cursor",
  " * Hides the cursor (`ESC[?25l`) — written before the driver starts redrawing a prompt so the cursor"),
 ("/** Show the cursor (`ESC[?25h`) — restores the cursor after a prompt resolves / cancels (the {@link CURSOR_HIDE} pair). */",
  "/** Shows the cursor (`ESC[?25h`) — restores the cursor after a prompt resolves / cancels (the {@link CURSOR_HIDE} pair). */"),
 (" * Erase from the cursor down to the end of the screen (`ESC[J`) — wipes the WHOLE previous (possibly",
  " * Erases from the cursor down to the end of the screen (`ESC[J`) — wipes the WHOLE previous (possibly"),
 ("/** A carriage return (`\\r`, U+000D) — returns the cursor to column 0 so a redraw starts at the line's left edge. */",
  "/** Names the carriage return byte (`\\r`, U+000D) — returns the cursor to column 0 so a redraw starts at the line's left edge. */"),
 ("/** A line feed (`\\n`, U+000A) — the line terminator the driver writes after the final committed prompt view. */",
  "/** Names the line feed byte (`\\n`, U+000A) — the line terminator the driver writes after the final committed prompt view. */"),
 (" * The numbered-list prompt the non-TTY {@link import('./Terminal.js').Terminal} `select` fallback",
  " * Holds the numbered-list prompt the non-TTY {@link import('./Terminal.js').Terminal} `select` fallback"),
 ("/** The comma-separated multi-select hint the non-TTY `checkbox` fallback shows (the user types one or more numbers). */",
  "/** Holds the comma-separated multi-select hint the non-TTY `checkbox` fallback shows (the user types one or more numbers). */"),
 ("/** The hint the non-TTY `editor` fallback shows — a piped stream has no ctrl-d, so end of input finishes the block. */",
  "/** Holds the hint the non-TTY `editor` fallback shows — a piped stream has no ctrl-d, so end of input finishes the block. */"),
 ("/** The hint the non-TTY `confirm` fallback shows — a piped stream sends a whole line, so the answer is typed rather than pressed. */",
  "/** Holds the hint the non-TTY `confirm` fallback shows — a piped stream sends a whole line, so the answer is typed rather than pressed. */"),
 (" * The format cue appended to a field's label for each control the walk reads as a line of text —",
  " * Holds the format cue appended to a field's label for each control the walk reads as a line of text —"),
 ("/** The instruction a `file` field with `multiple` shows before its entries — one path per line, and a blank line ends the list. */",
  "/** Holds the instruction a `file` field with `multiple` shows before its entries — one path per line, and a blank line ends the list. */"),
 ("/** The lead on the line listing an open `select`'s offered values, which a typed answer may ignore. */",
  "/** Holds the lead on the line listing an open `select`'s offered values, which a typed answer may ignore. */"),
 ("/** The lead on the line listing the choices a `select` or `checkbox` shows but refuses, so a reader sees why one is missing from the list below. */",
  "/** Holds the lead on the line listing the choices a `select` or `checkbox` shows but refuses, so a reader sees why one is missing from the list below. */"),
 ("/** The mark on a locked field's line — the walk renders its value and moves on, because the form refuses an edit there. */",
  "/** Holds the mark on a locked field's line — the walk renders its value and moves on, because the form refuses an edit there. */"),
 (" * What a field is told when the walk read an answer the control cannot hold — a word typed into a",
  " * States what a field is told when the walk read an answer the control cannot hold — a word typed into a"),
])
apply('/home/user/fleet/terminal/src/server/factories.ts', [
 (" * Create the interactive terminal form driver — the local-keyboard arm of the terminal trio, beside",
  " * Creates the interactive terminal form driver — the local-keyboard arm of the terminal trio, beside"),
])
apply('/home/user/fleet/terminal/src/server/helpers.ts', [
 (" * Whether `value` is a usable {@link InputStreamInterface} — a record with callable `on` / `off`",
  " * Checks whether `value` is a usable {@link InputStreamInterface} — a record with callable `on` / `off`"),
 (" * @returns `true` when `value` has callable `on` and `off`",
  " * @returns True if `value` has callable `on` and `off`; false otherwise"),
 (" * Whether `value` is a usable {@link OutputStreamInterface} — a record with a callable `write`. A",
  " * Checks whether `value` is a usable {@link OutputStreamInterface} — a record with a callable `write`. A"),
 (" * @returns `true` when `value` has a callable `write`",
  " * @returns True if `value` has a callable `write`; false otherwise"),
 (" * Whether `value` is a Node {@link NodeJS.ReadableStream} — a total structural guard",
  " * Checks whether `value` is a Node {@link NodeJS.ReadableStream} — a total structural guard"),
 (" * @returns `true` when `value` has the readable methods readline needs",
  " * @returns True if `value` has the readable methods readline needs; false otherwise"),
 (" * @returns `true` when the stream is a TTY with `setRawMode`",
  " * @returns True if the stream is a TTY with `setRawMode`; false otherwise"),
 (" * The number of terminal LINES a rendered prompt `view` occupies — one more than its newline count",
  " * Counts the terminal LINES a rendered prompt `view` occupies — one more than its newline count"),
 (" * The cursor-UP control sequence that moves the cursor up `count` lines (`ESC[{count}A`) — or the",
  " * Returns the cursor-UP control sequence that moves the cursor up `count` lines (`ESC[{count}A`) — or the"),
 (" * The full reposition-and-clear prefix to write BEFORE re-rendering a prompt view in place — given",
  " * Returns the full reposition-and-clear prefix to write BEFORE re-rendering a prompt view in place — given"),
 (" * Project any field the walk reads as a LINE OF TEXT into the {@link TextField} the text reducer",
  " * Projects any field the walk reads as a LINE OF TEXT into the {@link TextField} the text reducer"),
 (" * Project one held answer into the text a read-only line shows — a scalar as itself, a boolean as",
  " * Projects one held answer into the text a read-only line shows — a scalar as itself, a boolean as"),
])
