# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, '/home/user/scaffold/tmp/units/voice/edits')
from apply import apply
P = '/home/user/fleet/terminal/src/server/Terminal.ts'
pairs = [
 (" * The interactive terminal form DRIVER — the {@link TerminalInterface} implementation for a human at\n * this machine's keyboard, and the only impure part of the terminal stack. {@link ask} walks one\n",
  " * Implements {@link TerminalInterface} for a human at this machine's keyboard — the interactive form\n * DRIVER, and the only impure part of the terminal stack. {@link ask} walks one\n"),
 ("\t * Ask `fields` in the order given, skipping what the walk must not touch and rendering what it",
  "\t * Asks `fields` in the order given, skipping what the walk must not touch and rendering what it"),
 ("/** Write a group's label as a section header, resolving the schema's declared label and falling back to the group's own name. */",
  "/** Writes a group's label as a section header, resolving the schema's declared label and falling back to the group's own name. */"),
 ("/** Render a locked field read-only — its label, its mark, and the answer the form already holds. */",
  "/** Renders a locked field read-only — its label, its mark, and the answer the form already holds. */"),
 ("/** Read one field through the reducer its control names, resolving the raw answer the binding projects. */",
  "/** Reads one field through the reducer its control names, resolving the raw answer the binding projects. */"),
 ("\t * Bind one raw answer to the form — the single binding, and the only place this driver writes a",
  "\t * Binds one raw answer to the form — the single binding, and the only place this driver writes a"),
 ("/** The erroring fields the walk can ask again — every field the walk skips or renders read-only is excluded, because a second pass could not change its answer. */",
  "/** Collects the erroring fields the walk can ask again — every field the walk skips or renders read-only is excluded, because a second pass could not change its answer. */"),
 ("/** Write every supplied failure against its field's label. */",
  "/** Writes every supplied failure against its field's label. */"),
 ("/** Read a field as one line of text — `text` itself and the six controls a terminal has no widget for. */",
  "/** Reads a field as one line of text — `text` itself and the six controls a terminal has no widget for. */"),
 ("/** Read a secret — masked live in raw mode, and read without echo through readline on a stream that cannot enter it. */",
  "/** Reads a secret — masked live in raw mode, and read without echo through readline on a stream that cannot enter it. */"),
 ("\t * Read a yes or no. The fallback accepts", "\t * Reads a yes or no. The fallback accepts"),
 ("/** Read text over many lines — ctrl-d finishes in raw mode, and end of input finishes on a piped stream. */",
  "/** Reads text over many lines — ctrl-d finishes in raw mode, and end of input finishes on a piped stream. */"),
 ("\t * Read one choice. A disabled choice is named above the list", "\t * Reads one choice. A disabled choice is named above the list"),
 ("\t * Read any number of choices. Disabled choices are named above the list", "\t * Reads any number of choices. Disabled choices are named above the list"),
 ("\t * Read file paths — names only, because bytes never enter a form.", "\t * Reads file paths — names only, because bytes never enter a form."),
 ("/** Name the choices a field shows but refuses, above the list the walk drives. */",
  "/** Names the choices a field shows but refuses, above the list the walk drives. */"),
 ("/** Write a field's header above its numbered choice list — the non-TTY presentation of a choice field. */",
  "/** Writes a field's header above its numbered choice list — the non-TTY presentation of a choice field. */"),
 ("/** Paint one line of supplementary instruction through the `hint` role. */",
  "/** Paints one line of supplementary instruction through the `hint` role. */"),
 ("\t * The irreducible Node raw-mode primitive — the ONLY place raw mode is touched. Switches the input",
  "\t * Isolates the irreducible Node raw-mode primitive — the ONLY place raw mode is touched. Switches the input"),
 ("\t * Drive ONE field over raw-mode stdin — the generic engine every interactive control shares.",
  "\t * Drives ONE field over raw-mode stdin — the generic engine every interactive control shares."),
 ("/** End an active read that the form outlived — release raw mode exactly as a submit does, then fail the read with the form's own error. */",
  "/** Ends an active read that the form outlived — releases raw mode exactly as a submit does, then fails the read with the form's own error. */"),
 ("/** Redraw a field view in place — climb over the previous view's `previousLines`, clear, and write the new view (the pure cursor-math is {@link redrawPrefix}). */",
  "/** Redraws a field view in place — climbs over the previous view's `previousLines`, clears, and writes the new view (the pure cursor-math is {@link redrawPrefix}). */"),
 ("/** Read one line for a text-shaped field, taking the field's default when the line is bare. */",
  "/** Reads one line for a text-shaped field, taking the field's default when the line is bare. */"),
 ("\t * Read a whole block for an `editor` field — a piped stream has no ctrl-d keypress, so end of",
  "\t * Reads a whole block for an `editor` field — a piped stream has no ctrl-d keypress, so end of"),
 ("/** Write one field's header and read back the line the reader answers it with, or `''` once the stream has ended. */",
  "/** Writes one field's header and reads back the line the reader answers it with, or `''` once the stream has ended. */"),
 ("\t * Take the next line the input carries — from the buffer when the reader has already read ahead,",
  "\t * Takes the next line the input carries — from the buffer when the reader has already read ahead,"),
 ("\t * Open the walk's ONE readline interface, or keep the open one. A whole form is many questions",
  "\t * Opens the walk's ONE readline interface, or keeps the open one. A whole form is many questions"),
 ("/** Hand a line to whoever is waiting for it, or buffer it for the next question. */",
  "/** Hands a line to whoever is waiting for it, or buffers it for the next question. */"),
 ("/** Record that no further line can arrive and release whoever was waiting for one. */",
  "/** Records that no further line can arrive and releases whoever was waiting for one. */"),
 ("/** Close the walk's reader and release a waiting question — the walk is over, so the stream must stop holding the process open. */",
  "/** Closes the walk's reader and releases a waiting question — the walk is over, so the stream must stop holding the process open. */"),
 ("\t * Narrow the resolved input to the `node:readline` `createInterface` boundary, never an assertion.",
  "\t * Narrows the resolved input to the `node:readline` `createInterface` boundary, never an assertion."),
]
apply(P, pairs)
