#!/bin/bash
# Fleet branch cleanup — run from any machine with push credentials.
#
# This deletes remote branches. Read it before running it.
#
# Every branch named below was verified: the MERGED tips are ancestors of
# origin/main, and the unmerged ones were ruled delete-worthy on
# 2026-08-17 (a net-empty revert pair, an obsolete re-pin, and one merged as a
# pull request and then rewritten).
#
# Corrected on 2026-08-20: the generator emitted one `--delete origin` line per
# repository, which asked each remote to delete a branch literally named
# `origin`. Those lines were removed. Nothing else changed, and no line
# that names a real branch was touched.
git push https://github.com/orkestrel/abort --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/abort --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/abort --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/abort --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/abort --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/abort --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/agent --delete claude/agent-context-refactor-vils1l
git push https://github.com/orkestrel/agent --delete claude/agent-production-audit-nfh5yc
git push https://github.com/orkestrel/agent --delete claude/agent-production-audit-q949ej
git push https://github.com/orkestrel/agent --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/agent --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/agent --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/agent --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/agent --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/agent --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/agent --delete claude/workflow-enterprise-audit-f6zo2k
git push https://github.com/orkestrel/browser --delete claude/browser-orkestrel-conversion-4re809
git push https://github.com/orkestrel/browser --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/browser --delete claude/orkestrel-html-package-bwsp9p
git push https://github.com/orkestrel/browser --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/browser --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/browser --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/browser --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/budget --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/budget --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/budget --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/budget --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/budget --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/budget --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/console --delete claude/console-orkestrel-conversion-6dzfsp
git push https://github.com/orkestrel/console --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/console --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/console --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/console --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/console --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/console --delete claude/terminal-console-enterprise-audit-c6tqrd
git push https://github.com/orkestrel/contract --delete claude/json-schema-opaque-parsing-a9dzcg
git push https://github.com/orkestrel/contract --delete claude/markdown-parser-production-l6utfy
git push https://github.com/orkestrel/contract --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/contract --delete claude/orkestrel-foundation-cleanup-rytvez
git push https://github.com/orkestrel/contract --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/contract --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/contract --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/contract --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/contract --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/contract --delete claude/strict-domain-channel
git push https://github.com/orkestrel/contract --delete claude/workflow-enterprise-audit-f6zo2k
git push https://github.com/orkestrel/csv --delete claude/csv-parser-renderer-b60ebu
git push https://github.com/orkestrel/csv --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/csv --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/csv --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/csv --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/csv --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/database --delete claude/database-package-audit-6r4hsd
git push https://github.com/orkestrel/database --delete claude/database-repo-cleanup-n6sobc
git push https://github.com/orkestrel/database --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/database --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/database --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/database --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/database --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/database --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/database --delete claude/uuid-generator-refactor-dsyl9i
git push https://github.com/orkestrel/emitter --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/emitter --delete claude/orkestrel-html-package-bwsp9p
git push https://github.com/orkestrel/emitter --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/emitter --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/emitter --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/emitter --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/emitter --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/form --delete claude/form-abstraction-audit-gex32w
git push https://github.com/orkestrel/guide --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/guide --delete claude/orkestrel-html-package-bwsp9p
git push https://github.com/orkestrel/guide --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/guide --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/guide --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/guide --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/guide --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/html --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/html --delete claude/orkestrel-html-package-bwsp9p
git push https://github.com/orkestrel/html --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/indexeddb --delete claude/database-package-audit-6r4hsd
git push https://github.com/orkestrel/indexeddb --delete claude/database-repo-cleanup-n6sobc
git push https://github.com/orkestrel/indexeddb --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/indexeddb --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/indexeddb --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/indexeddb --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/indexeddb --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/indexeddb --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/interpret --delete claude/interpret-orkestrel-conversion
git push https://github.com/orkestrel/interpret --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/interpret --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/interpret --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/interpret --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/interpret --delete claude/orkestrel-template-manager-b9hhbv
git push https://github.com/orkestrel/interpret --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/markdown --delete claude/markdown-parser-production-l6utfy
git push https://github.com/orkestrel/markdown --delete claude/msg-package-redesign-9hgzd5
git push https://github.com/orkestrel/markdown --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/markdown --delete claude/orkestrel-html-package-bwsp9p
git push https://github.com/orkestrel/markdown --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/markdown --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/markdown --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/markdown --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/markdown --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/mcp --delete claude/agent-context-refactor-vils1l
git push https://github.com/orkestrel/mcp --delete claude/mcp-orkestrel-conversion
git push https://github.com/orkestrel/mcp --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/mcp --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/mcp --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/mcp --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/mcp --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/mcp --delete claude/workflow-enterprise-audit-f6zo2k
git push https://github.com/orkestrel/middleware --delete claude/middleware-windows-tests-audit-qln0p3
git push https://github.com/orkestrel/middleware --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/middleware --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/middleware --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/middleware --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/middleware --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/middleware --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/middleware --delete claude/server-router-middleware-integration-arbn3c
git push https://github.com/orkestrel/msg --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/msg --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/msg --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/msg --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/msg --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/ndjson --delete claude/ndjson-package-conversion-hocg64
git push https://github.com/orkestrel/ndjson --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/ndjson --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/ndjson --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/ndjson --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/ndjson --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/ollama --delete claude/agent-context-refactor-vils1l
git push https://github.com/orkestrel/ollama --delete claude/agent-diagnostics-models-ttecxq
git push https://github.com/orkestrel/ollama --delete claude/agent-production-audit-nfh5yc
git push https://github.com/orkestrel/ollama --delete claude/agent-production-audit-q949ej
git push https://github.com/orkestrel/ollama --delete claude/ollama-orkestrel-refactor-z94bcg
git push https://github.com/orkestrel/ollama --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/ollama --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/ollama --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/ollama --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/pool --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/pool --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/pool --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/pool --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/pool --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/pool --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/program --delete claude/fix-test-types-p78x3h
git push https://github.com/orkestrel/program --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/program --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/program --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/program --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/program --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/program --delete claude/program-package-audit-ckx96m
git push https://github.com/orkestrel/qualifier --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/qualifier --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/qualifier --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/qualifier --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/qualifier --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/qualifier --delete claude/qualifier-audit-hardening-i34u0n
git push https://github.com/orkestrel/queue --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/queue --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/queue --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/queue --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/queue --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/queue --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/rater --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/rater --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/rater --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/rater --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/rater --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/rater --delete claude/rater-audit-hardening-ml7oac
git push https://github.com/orkestrel/rater --delete claude/rater-orkestrel-conversion-jhuqam
git push https://github.com/orkestrel/reason --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/reason --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/reason --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/reason --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/reason --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/reason --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/reason --delete claude/rater-orkestrel-conversion-jhuqam
git push https://github.com/orkestrel/relation --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/relation --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/relation --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/relation --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/relation --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/relation --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/router --delete claude/agent-context-refactor-vils1l
git push https://github.com/orkestrel/router --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/router --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/router --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/router --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/router --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/router --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/router --delete claude/server-router-middleware-integration-arbn3c
git push https://github.com/orkestrel/sea --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/sea --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/sea --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/sea --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/sea --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/sea --delete claude/package-audit-hardening-sj1wwk
git push https://github.com/orkestrel/sea --delete claude/sea-orkestrel-conversion-izrbe0
git push https://github.com/orkestrel/server --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/server --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/server --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/server --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/server --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/server --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/server --delete claude/server-router-middleware-integration-arbn3c
git push https://github.com/orkestrel/sqlite --delete claude/database-package-audit-6r4hsd
git push https://github.com/orkestrel/sqlite --delete claude/database-repo-cleanup-n6sobc
git push https://github.com/orkestrel/sqlite --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/sqlite --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/sqlite --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/sqlite --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/sqlite --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/sqlite --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/sse --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/sse --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/sse --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/sse --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/sse --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/sse --delete claude/sse-orkestrel-conversion-i2spsj
git push https://github.com/orkestrel/supervisor --delete claude/form-abstraction-audit-gex32w
git push https://github.com/orkestrel/supervisor --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/supervisor --delete claude/plan-folder-audit-2wtr80
git push https://github.com/orkestrel/table --delete claude/form-abstraction-audit-gex32w
git push https://github.com/orkestrel/template --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/template --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/template --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/template --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/template --delete claude/orkestrel-template-manager-b9hhbv
git push https://github.com/orkestrel/template --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/terminal --delete claude/console-orkestrel-conversion-6dzfsp
git push https://github.com/orkestrel/terminal --delete claude/form-abstraction-audit-gex32w
git push https://github.com/orkestrel/terminal --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/terminal --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/terminal --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/terminal --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/terminal --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/terminal --delete claude/terminal-console-enterprise-audit-c6tqrd
git push https://github.com/orkestrel/terminal --delete claude/workflow-enterprise-audit-f6zo2k
git push https://github.com/orkestrel/test --delete claude/form-abstraction-audit-gex32w
git push https://github.com/orkestrel/test --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/timeout --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/timeout --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/timeout --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/timeout --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/timeout --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/timeout --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/tool --delete claude/agent-context-refactor-vils1l
git push https://github.com/orkestrel/tool --delete claude/json-schema-opaque-parsing-a9dzcg
git push https://github.com/orkestrel/tool --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/tool --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/tool --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/tool --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/tool --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/tool --delete claude/workflow-enterprise-audit-f6zo2k
git push https://github.com/orkestrel/toolbox --delete claude/agent-context-refactor-vils1l
git push https://github.com/orkestrel/toolbox --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/toolbox --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/websocket --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/websocket --delete claude/orkestrel-html-package-bwsp9p
git push https://github.com/orkestrel/websocket --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/websocket --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/websocket --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/websocket --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/websocket --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/worker --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/worker --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/worker --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/worker --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/worker --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/worker --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/workflow --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/workflow --delete claude/orkestrel-orchestration-k2zfqp
git push https://github.com/orkestrel/workflow --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/workflow --delete claude/orkestrel-package-orchestration-v9qcqf
git push https://github.com/orkestrel/workflow --delete claude/orkestrel-packages-audit-3rjcf7
git push https://github.com/orkestrel/workflow --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/workflow --delete claude/workflow-enterprise-audit-f6zo2k
git push https://github.com/orkestrel/workspace --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/workspace --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/scaffold --delete claude/agent-context-refactor-vils1l
git push https://github.com/orkestrel/scaffold --delete claude/form-abstraction-audit-gex32w
git push https://github.com/orkestrel/scaffold --delete claude/orkestrel-fleet-orchestration-cv30e8
git push https://github.com/orkestrel/scaffold --delete claude/orkestrel-html-package-bwsp9p
git push https://github.com/orkestrel/scaffold --delete claude/orkestrel-orchestration-tp0ez7
git push https://github.com/orkestrel/scaffold --delete claude/orkestrel-test-package-0m1m8u
git push https://github.com/orkestrel/scaffold --delete claude/s22-release
git push https://github.com/orkestrel/scaffold --delete probe-push-isolate
git push https://github.com/orkestrel/contract --delete claude/orkestrel-html-package-bwsp9p
git push https://github.com/orkestrel/database --delete claude/workflow-enterprise-audit-f6zo2k
git push https://github.com/orkestrel/mcp --delete claude/json-schema-opaque-parsing-a9dzcg
