#!/bin/bash
# Re-run scaffold's preparation gates after the snapshot tripwire moved with the bump: format, prepublishOnly, dist
# comparison. Manifest and lockfile already re-pinned and regenerated by prep-scaffold.sh. Log: prep-scaffold-4.log.
set -u
export PATH=/opt/npm11/bin:$PATH
W=/home/user/work/wave; LOG=$W/prep-scaffold-4.log; : > "$LOG"
say() { echo "$(date -u +%H:%M:%S) $*" >> "$LOG"; }
cd /home/user/scaffold || exit 2
say "version $(node -p "require('./package.json').version"); dirty: $(git status --porcelain | tr '\n' ' ')"
npm run format > "$W/prep-scaffold-4-format.log" 2>&1; say "format exit=$?"
npm run prepublishOnly > "$W/prep-scaffold-4-prepublish.log" 2>&1; rc=$?; say "prepublishOnly exit=$rc"
[ $rc -eq 0 ] || { say "RED"; grep -E '^ FAIL |error TS|Error:' "$W/prep-scaffold-4-prepublish.log" | head -20 >> "$LOG"; exit 1; }
say "dist against published: $(node /home/user/work/distdiff.mjs /home/user/scaffold | cut -c1-300)"
git status --porcelain >> "$LOG"
say "PREP-scaffold-GATES-GREEN"
