#!/usr/bin/env bash
set -euo pipefail
source /c/Users/mikes/WebstormProjects/scaffold/tmp/pass/pass-env.sh
package=${1-}; expected=${2-}; version=${3-}; visit=${4-}; label=${5-}; target="$FLEET/$package"; out="$SCR/$label"
fail(){ printf '%s\n' "$1" >&2; exit 1; }
capture(){ local suffix="$1"; git -C "$target" branch --show-current > "$out/branch-$suffix.txt"; git -C "$target" rev-parse HEAD > "$out/head-$suffix.txt"; git -C "$target" status --porcelain=v1 --untracked-files=all > "$out/status-$suffix.txt"; git -C "$target" diff HEAD --binary > "$out/diff-$suffix.txt"; git -C "$target" ls-files --stage > "$out/index-$suffix.txt"; sha256sum "$target/package.json" "$target/package-lock.json" > "$out/manifests-$suffix.sha256"; }
case "$package" in abort|budget|csv|emitter|html|indexeddb|ndjson|sqlite|timeout|tool);; *) fail 'package is outside the confirmed next layer';; esac
[[ "$expected" =~ ^[0-9a-f]{40}$ && "$label" =~ ^[[:alnum:]][[:alnum:]._-]*$ ]] || fail 'expected HEAD or label is unsafe'; test -d "$target/.git" || fail 'canonical target is absent'; test ! -e "$out" || fail 'closure evidence exists'; test "$(node "$SCR/read-package-field.mjs" "$target/package.json" name)" = "@orkestrel/$package" || fail 'manifest name differs'; test "$(node "$SCR/read-package-field.mjs" "$target/package.json" version)" = "$version" || fail 'manifest version differs'; test "$(git -C "$target" branch --show-current)" = claude/orkestrel-npm-audit-deps-14ibta || fail 'campaign branch differs'; test "$(git -C "$target" rev-parse HEAD)" = "$expected" || fail 'source HEAD differs'; test -z "$(git -C "$target" status --porcelain=v1 --untracked-files=all)" || fail 'input tree must be clean'
pack="$SCR/packed/$visit-pack"; prepublish="$SCR/$visit-prepublish"; test "$(<"$SCR/$visit/pack.exit.txt")" = 0; test "$(<"$prepublish/action.exit.txt")" = 0; cmp "$SCR/$visit/manifests-after.sha256" <(sha256sum "$target/package.json" "$target/package-lock.json"); cmp "$SCR/$visit/diff-after.txt" <(git -C "$target" diff HEAD --binary); cmp "$SCR/$visit/index-after.txt" <(git -C "$target" ls-files --stage); cmp "$pack/extract/package/package.json" "$target/package.json"; diff -r "$pack/extract/package/dist" "$target/dist" > /dev/null; sha256sum --check "$pack/archive.sha256" > /dev/null; test ! -e "$target/scripts/docs.ts"; node "$SCR/validate-next-release.mjs" "$target/package.json" "$package" "$version" > /dev/null
mkdir "$out"; capture before; timeout --kill-after=15s 60s git -C "$target" fetch origin > "$out/fetch.stdout.txt" 2> "$out/fetch.stderr.txt" || status=$?; printf '%s\n' "${status:-0}" > "$out/fetch.exit.txt"; test "${status:-0}" -eq 0; git -C "$target" merge-base --is-ancestor origin/main HEAD; changed="$(git -C "$target" diff --name-only HEAD)"; while IFS= read -r path; do case "$path" in package.json|package-lock.json|.claude/agents/orkestrel.md|guides/*.md) case "$path" in "guides/$package.md") fail 'own guide changed';; esac;; scripts/docs.ts) ;; '') ;; *) fail "changed path is not allowed: $path";; esac; done <<< "$changed"; git -C "$target" add -- package.json package-lock.json .claude/agents/orkestrel.md guides scripts/docs.ts; git -C "$target" -c user.name=Claude -c user.email=noreply@anthropic.com commit -m "Prepare $package release" -m "Co-Authored-By: Claude <noreply@anthropic.com>" -m "Claude-Session: codex:01a0810d-21bf-7f60-8534-488348e05743"; git -C "$target" push -u origin claude/orkestrel-npm-audit-deps-14ibta; git -C "$target" push origin HEAD:main; git -C "$target" switch main; git -C "$target" merge --ff-only origin/main; test -z "$(git -C "$target" status --porcelain=v1 --untracked-files=all)"; capture after; cmp "$pack/extract/package/package.json" "$target/package.json"; diff -r "$pack/extract/package/dist" "$target/dist" > /dev/null; printf '%s\n' "$out"
