#!/usr/bin/env bash
set -euo pipefail
# Successor: stage published tooling for dependent native parity adoption.
source /c/Users/mikes/WebstormProjects/scaffold/tmp/pass/pass-env.sh
package=${1-}; label=${2-}; guide_label=${3-}; guide_hash=${4-}; scaffold_label=${5-}; scaffold_hash=${6-}
target="$FLEET/$package"; out="$SCR/$label"; guide="$SCR/packed/$guide_label/orkestrel-guide-0.0.18.tgz"; guide_extract="$SCR/packed/$guide_label/extract/package"; scaffold="$SCR/packed/$scaffold_label/orkestrel-scaffold-0.0.64.tgz"; scaffold_extract="$SCR/packed/$scaffold_label/extract/package"
fail(){ printf '%s\n' "$1" >&2; exit 1; }
case "$package" in brief|mcp|middleware|program|worker|workflow) ;; *) fail 'package is outside the dependent tooling layer' ;; esac
for value in "$label" "$guide_label" "$scaffold_label"; do [[ "$value" =~ ^[[:alnum:]][[:alnum:]._-]*$ ]] || fail 'evidence label must be safe'; done
for value in "$guide_hash" "$scaffold_hash"; do [[ "$value" =~ ^[[:xdigit:]]{64}$ ]] || fail 'archive SHA256 must be hexadecimal'; done
test -d "$target/.git" || fail 'canonical target is absent'; test ! -e "$out" || fail 'evidence output exists'; test "$(node "$SCR/read-package-field.mjs" "$target/package.json" name)" = "@orkestrel/$package" || fail 'manifest name differs'
for archive in "$guide" "$scaffold"; do test -f "$archive" || fail "archive is absent: $archive"; done
test "$(sha256sum "$guide" | cut -d ' ' -f 1)" = "${guide_hash,,}" || fail 'Guide archive hash differs'; test "$(sha256sum "$scaffold" | cut -d ' ' -f 1)" = "${scaffold_hash,,}" || fail 'Scaffold archive hash differs'
test "$(node "$SCR/read-package-field.mjs" "$guide_extract/package.json" name)" = '@orkestrel/guide' || fail 'Guide archive name differs'; test "$(node "$SCR/read-package-field.mjs" "$guide_extract/package.json" version)" = '0.0.18' || fail 'Guide archive version differs'; test -d "$guide_extract/dist" || fail 'Guide archive dist is absent'
test "$(node "$SCR/read-package-field.mjs" "$scaffold_extract/package.json" name)" = '@orkestrel/scaffold' || fail 'Scaffold archive name differs'; test "$(node "$SCR/read-package-field.mjs" "$scaffold_extract/package.json" version)" = '0.0.64' || fail 'Scaffold archive version differs'; test -d "$scaffold_extract/dist" || fail 'Scaffold archive dist is absent'
mkdir "$out"; sha256sum "$guide" "$scaffold" > "$out/archives.sha256"; cp "$target/package.json" "$out/package-before.json"; git -C "$target" rev-parse HEAD > "$out/head-before.txt"; git -C "$target" status --porcelain=v1 > "$out/status-before.txt"; git -C "$target" ls-files --stage > "$out/index-before.txt"; sha256sum "$target/package.json" "$target/package-lock.json" > "$out/manifests-before.sha256"
status=0
if [ "$package" = guide ]; then if timeout --kill-after=15s 600s npm --prefix "$target" install --no-save --ignore-scripts "$scaffold" @orkestrel/test@0.0.14 > "$out/install.stdout.txt" 2> "$out/install.stderr.txt"; then status=0; else status=$?; fi; else if timeout --kill-after=15s 600s npm --prefix "$target" install --no-save --ignore-scripts "$guide" "$scaffold" @orkestrel/test@0.0.14 > "$out/install.stdout.txt" 2> "$out/install.stderr.txt"; then status=0; else status=$?; fi; fi
printf '%s\n' "$status" > "$out/install.exit.txt"; git -C "$target" rev-parse HEAD > "$out/head-after.txt"; git -C "$target" status --porcelain=v1 > "$out/status-after.txt"; git -C "$target" ls-files --stage > "$out/index-after.txt"; sha256sum "$target/package.json" "$target/package-lock.json" > "$out/manifests-after.sha256"; cp "$target/package.json" "$out/package-after.json"; cmp "$out/head-before.txt" "$out/head-after.txt"; cmp "$out/status-before.txt" "$out/status-after.txt"; cmp "$out/index-before.txt" "$out/index-after.txt"; cmp "$out/manifests-before.sha256" "$out/manifests-after.sha256"; test "$status" -eq 0
if [ "$package" != guide ]; then if diff -r "$guide_extract/dist" "$target/node_modules/@orkestrel/guide/dist" > "$out/guide-dist.diff.txt"; then printf '0\n' > "$out/guide-dist.exit.txt"; else status=$?; printf '%s\n' "$status" > "$out/guide-dist.exit.txt"; exit "$status"; fi; fi
if diff -r "$scaffold_extract/dist" "$target/node_modules/@orkestrel/scaffold/dist" > "$out/scaffold-dist.diff.txt"; then printf '0\n' > "$out/scaffold-dist.exit.txt"; else status=$?; printf '%s\n' "$status" > "$out/scaffold-dist.exit.txt"; exit "$status"; fi
status=0; if npm --prefix "$target" ls @orkestrel/guide @orkestrel/scaffold @orkestrel/test --all --json > "$out/npm-ls.json" 2> "$out/npm-ls.stderr.txt"; then status=0; else status=$?; fi; printf '%s\n' "$status" > "$out/npm-ls.exit.txt"; printf '%s\n' "$out"
