#!/usr/bin/env bash
set -euo pipefail
source /c/Users/mikes/WebstormProjects/scaffold/tmp/pass/pass-env.sh
label=${1-}; guide="$FLEET/guide"; out="$SCR/$label"; scaffold="$SCAFFOLD"; pack="$SCR/packed/d7n-scaffold-upper-git-final-pack"; guide_pack="$SCR/packed/d7n-guide-upper-final-pack"; result="$SCR/d7n-scaffold-registry-confirm-closed/result.json"
fail(){ printf '%s\n' "$1" >&2; exit 1; }
run(){ local name="$1" cap="$2"; shift 2; local status=0; if (cd "$guide" && timeout --kill-after=15s "$cap" "$@") > "$out/$name.stdout.txt" 2> "$out/$name.stderr.txt"; then status=0; else status=$?; fi; printf '%s\n' "$status" > "$out/$name.exit.txt"; printf '%q ' "$@" >> "$out/commands.txt"; printf '\n' >> "$out/commands.txt"; return "$status"; }
gitrun(){ local name="$1" cap="$2"; shift 2; run "$name" "$cap" git -C "$guide" "$@"; }
[[ "$label" =~ ^[[:alnum:]][[:alnum:]._-]*$ ]] || fail 'evidence label is unsafe'; test ! -e "$out" || fail 'evidence exists'; test -f "$result" || fail 'Scaffold registry confirmation is absent'; grep -F 'a4e7078da602619e54384dbc7bdddaf25a2fdc6af0842a55004b8328365b8be7' "$result" > /dev/null || fail 'Scaffold registry confirmation differs'; mkdir "$out"
gitrun branch 120s branch --show-current; test "$(<"$out/branch.stdout.txt")" = claude/orkestrel-npm-audit-deps-14ibta || fail 'Guide branch differs'; gitrun head 120s rev-parse HEAD; test "$(<"$out/head.stdout.txt")" = f277b88bc1e8063521ce1acaa783913b0af1856a || fail 'Guide HEAD differs'; gitrun index 120s diff --cached --quiet; test "$(<"$out/index.exit.txt")" = 0 || fail 'Guide index is not empty'; gitrun status 120s status --porcelain=v1 --untracked-files=all; test ! -s "$out/status.stdout.txt" || fail 'Guide tree is not clean'; test "$(node "$SCR/read-package-field.mjs" "$guide/package.json" version)" = 0.0.18 || fail 'Guide version differs'
run contract-pin 120s npm pkg get dependencies.@orkestrel/contract; test "$(<"$out/contract-pin.stdout.txt")" = '"^0.0.17"' || fail 'Guide Contract pin differs'; run markdown-pin 120s npm pkg get dependencies.@orkestrel/markdown; test "$(<"$out/markdown-pin.stdout.txt")" = '"^0.0.14"' || fail 'Guide Markdown pin differs'; run test-pin 120s npm pkg get devDependencies.@orkestrel/test; test "$(<"$out/test-pin.stdout.txt")" = '"^0.0.14"' || fail 'Guide Test pin differs'
gitrun diff-baseline 120s diff HEAD --binary; gitrun index-baseline 120s ls-files --stage; sha256sum "$guide/package.json" "$guide/package-lock.json" > "$out/manifests-before.sha256"; sha256sum "$guide/guides/guide.md" > "$out/guide-before.sha256"
run registry-guide 120s npm view @orkestrel/guide@0.0.17 version; test "$(<"$out/registry-guide.stdout.txt")" = 0.0.17 || fail 'Guide registry version differs'; run registry-scaffold 120s npm view @orkestrel/scaffold@0.0.64 version; test "$(<"$out/registry-scaffold.stdout.txt")" = 0.0.64 || fail 'Scaffold registry version differs'; gitrun fetch 120s fetch origin; gitrun ancestry 120s merge-base --is-ancestor origin/main HEAD
run install-scaffold 600s npm install --save-dev --ignore-scripts @orkestrel/scaffold@^0.0.64; test "$(<"$out/install-scaffold.exit.txt")" = 0 || fail 'Scaffold registry install failed'; gitrun changed 120s diff --name-only; while IFS= read -r path; do case "$path" in package.json|package-lock.json) ;; *) fail "unexpected Scaffold install path: $path";; esac; done < "$out/changed.stdout.txt"; run scaffold-version 120s node "$SCR/read-package-field.mjs" "$guide/node_modules/@orkestrel/scaffold/package.json" version; test "$(<"$out/scaffold-version.stdout.txt")" = 0.0.64 || fail 'installed Scaffold version differs'; run scaffold-dist 120s diff -r "$pack/extract/package/dist" "$guide/node_modules/@orkestrel/scaffold/dist"; test "$(<"$out/scaffold-dist.exit.txt")" = 0 || fail 'installed Scaffold dist differs'
gitrun add 120s add -- package.json package-lock.json; gitrun commit 120s -c user.name=Claude -c user.email=noreply@anthropic.com commit -m 'Prepare Guide against published Scaffold' -m 'Co-Authored-By: Claude <noreply@anthropic.com>' -m 'Claude-Session: codex:01a0810d-21bf-7f60-8534-488348e05743'; gitrun push 120s push origin HEAD:claude/orkestrel-npm-audit-deps-14ibta; gitrun prepared-head 120s rev-parse HEAD
run overwrite 180s node node_modules/@orkestrel/scaffold/dist/bin/main.js overwrite; test "$(<"$out/overwrite.exit.txt")" = 0 || fail 'online overwrite failed'; run audit 180s node node_modules/@orkestrel/scaffold/dist/bin/main.js audit; test "$(<"$out/audit.exit.txt")" = 0 || fail 'online audit failed'; run docs-delete 120s npm pkg delete scripts.docs; test "$(<"$out/docs-delete.exit.txt")" = 0 || fail 'docs script deletion failed'; run native-manifest 120s node "$SCR/verify-upper-native-manifest.mjs" "$guide/package.json"; test ! -e "$guide/scripts/docs.ts" || fail 'docs script remains'; test ! -e "$guide/scripts/guides.ts" || fail 'guides script remains'; run scaffold-guide 120s cmp "$guide/guides/scaffold.md" "$scaffold/guides/scaffold.md"; test "$(<"$out/scaffold-guide.exit.txt")" = 0 || fail 'Scaffold guide mirror differs'; sha256sum "$guide/guides/guide.md" > "$out/guide-after-overwrite.sha256"; cmp "$out/guide-before.sha256" "$out/guide-after-overwrite.sha256"
for action in lock install; do run "$action" 600s bash "$SCR/upper-layer-action.sh" guide "$action" "$label-$action" 600s; test "$(<"$out/$action.exit.txt")" = 0 || fail "Guide $action failed"; done; run ci 600s npm ci --ignore-scripts; test "$(<"$out/ci.exit.txt")" = 0 || fail 'Guide ci failed'; run scaffold-final-version 120s node "$SCR/read-package-field.mjs" "$guide/node_modules/@orkestrel/scaffold/package.json" version; test "$(<"$out/scaffold-final-version.stdout.txt")" = 0.0.64 || fail 'final Scaffold version differs'; run scaffold-final-dist 120s diff -r "$pack/extract/package/dist" "$guide/node_modules/@orkestrel/scaffold/dist"; test "$(<"$out/scaffold-final-dist.exit.txt")" = 0 || fail 'final Scaffold dist differs'; run scaffold-ls 120s npm ls @orkestrel/scaffold --depth=0; test "$(<"$out/scaffold-ls.exit.txt")" = 0 || fail 'Scaffold resolution differs'; run format 120s bash "$SCR/upper-layer-action.sh" guide format "$label-format" 120s; run prepublish 900s bash "$SCR/upper-layer-action.sh" guide prepublish "$label-prepublish" 900s; test "$(<"$out/prepublish.exit.txt")" = 0 || fail 'Guide prepublish failed'; run pack 600s bash "$SCR/pack-upper-layer-final-verified.sh" guide "$label-pack" 0.0.18 "$label-prepublish" 0.0.17; test "$(<"$out/pack.exit.txt")" = 0 || fail 'Guide pack failed'; run guide-dist 120s diff -r "$guide_pack/extract/package/dist" "$guide/dist"; test "$(<"$out/guide-dist.exit.txt")" = 0 || fail 'Guide distribution differs from the accepted archive'; gitrun branch-final 120s branch --show-current; gitrun head-final 120s rev-parse HEAD; gitrun status-final 120s status --porcelain=v1 --untracked-files=all; gitrun diff-final 120s diff HEAD --binary; gitrun index-final 120s ls-files --stage; sha256sum "$guide/package.json" "$guide/package-lock.json" > "$out/manifests-final.sha256"; printf '%s\n' "$out"
