#!/usr/bin/env bash
# Unit CL5b on Astra, the sole writer in the Veneer checkout: extract the two declaration blocks
# duplicated across the element and component folders, and land the shared-block sweep as a
# standing proof so the rule stops needing an auditor. The briefs are staged at
# veneer/tmp/units/cl5b-brief.md and cl5b-brief-2.md (copied from scaffold/tmp/units and verified
# identical before launch), with the scope read and both measurement logs beside them; the report
# is written inside the unit's own root at cl5b-report.md and returned as the last
# message. Journal: tmp/codex/cl5b.jsonl. Cap: 2 hours.
VENEER="C:/Users/mikes/WebstormProjects/veneer"
HEAD_SHA=$(git -C "$VENEER" rev-parse --short HEAD)
cd "C:/Users/mikes/WebstormProjects/scaffold" || exit 9
timeout 7200 codex exec --json -C "$VENEER" --sandbox workspace-write --model gpt-6-astra -c 'model_reasoning_effort="high"' --output-last-message "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/cl5b-last.md" "You are the sol role on Astra, the sole writer in this checkout, C:/Users/mikes/WebstormProjects/veneer, whose HEAD is $HEAD_SHA (the CL5 landing commit) and whose tracked tree is clean. Open and follow ./tmp/units/cl5b-brief-2.md exactly; it is the effective brief over ./tmp/units/cl5b-brief.md, which you also open and follow for every section brief 2 does not change; together they are the whole assignment, and they name the law to read from C:/Users/mikes/WebstormProjects/scaffold before editing. The scope read whose amendments brief 2 folds in is beside them at ./tmp/units/cl5b-scope-read-report.md, and the two measurement readings the briefs rest on are at ./tmp/units/sweep-styles-authored.log.txt and ./tmp/units/sweep-styles-source-2.log.txt with the dependency-free reference instrument at ./tmp/units/sweep-styles-source-2.mjs; read that instrument as a reference and write the shipped function to this repository's rules rather than copying it. The dependency bar is absolute: this unit adds no package, package.json is off-limits, and source-map-js is undeclared here and must not be imported; stop and report if you believe a package is needed. You are the bench engine reading the brief inside your own CLI: perform the assignment directly and spawn nothing. Write the report the brief names at ./tmp/units/cl5b-report.md and return its full content as your final message, nothing else." < /dev/null > "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl5b.jsonl" 2> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl5b.err"
echo "exit=$?" >> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl5b.err"
