#!/usr/bin/env bash
# Unit CL6 on Astra, the sole writer in the Veneer checkout: the link component classes, the
# anchor's colour retune bound to the calibration record, and the showcase section that renders
# them. The briefs are staged at veneer/tmp/units/cl6-brief.md and cl6-brief-2.md (copied from
# scaffold/tmp/units and verified identical before launch), with the terrain map, the retune
# measurement, and the scope read beside them; the report is written inside the unit's own root at
# cl6-report-2.md and returned as the last message. Journal: tmp/codex/cl6-2.jsonl.
# Cap: 2 hours.
VENEER="C:/Users/mikes/WebstormProjects/veneer"
HEAD_SHA=$(git -C "$VENEER" rev-parse --short HEAD)
cd "C:/Users/mikes/WebstormProjects/scaffold" || exit 9
timeout 7200 codex exec --json -C "$VENEER" --sandbox workspace-write --model gpt-6-astra -c 'model_reasoning_effort="high"' --output-last-message "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/cl6-2-last.md" "You are the sol role on Astra, the sole writer in this checkout, C:/Users/mikes/WebstormProjects/veneer, whose HEAD is $HEAD_SHA (the CL5c landing commit) and whose tracked tree is clean. Open and follow ./tmp/units/cl6-brief-3.md exactly; it is the effective brief over ./tmp/units/cl6-brief-2.md and ./tmp/units/cl6-brief.md beneath it, which you also open and follow for every section brief 3 does not change; together they are the whole assignment, and they name the law to read from C:/Users/mikes/WebstormProjects/scaffold before editing. Three retained records sit beside them and you read all three before editing: ./tmp/units/cl6-scout-report.md is the terrain map of the link key, the anchor partial, the link tokens, and the record's anchor readings; ./tmp/units/cl6-retune-measurement.md is the Orchestrator's reading and the rulings it supports; ./tmp/units/cl6-scope-read-report.md is the scope read whose amendments brief 2 folds in. Note that the terrain map's line citations into src/styles/_tokens.scss and src/styles/_mixins.scss now run about six lines early because a later unit landed tokens ahead of the link block in both, so re-locate every declaration by its token name rather than by the map's line number; every fact the map states was re-confirmed. Two things decide this unit's shape and brief 2 states both: the link key carries two custom properties, so it is not admitted to the shipped set by the empty-properties branch and needs variable rows with proofs; and the opacity utilities you ship are what make Bootstrap's dormant link-opacity variable live, which changes the anchor's behaviour and needs its own proof rather than riding on a presence scan. Obligation 1 is closed by brief 3: the hover mechanism is measured and the binding is stated, and ./tmp/units/cl6-hover-mechanism.md carries the reading. Measure the blast radius before the retune, not after: the link-styled button reads the link tokens and its proof pins the readings they produce today, and brief 2 grants that proof for those two assertions alone. A standing proof sweeps every style partial for a declaration block shared by two partials; if your work trips it, that is a real finding about your own change. You are the bench engine reading the brief inside your own CLI: perform the assignment directly and spawn nothing. Write the report the brief names at ./tmp/units/cl6-report-2.md and return its full content as your final message, nothing else." < /dev/null > "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl6-2.jsonl" 2> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl6-2.err"
echo "exit=$?" >> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl6-2.err"
