#!/usr/bin/env bash
# Unit CL7 on Astra, the sole writer in the Veneer checkout: the container classes with their
# breakpoint-scoped maximum widths, the container and gutter tokens, and the layout showcase
# section. The briefs are staged at veneer/tmp/units/cl7-brief.md and cl7-brief-2.md (copied from
# scaffold/tmp/units and verified identical before launch), with the terrain map, the rulings, and
# the scope read beside them; the report is written inside the unit's own root at
# cl7-report.md and returned as the last message. Journal: tmp/codex/cl7.jsonl.
# Cap: 2 hours.
VENEER="C:/Users/mikes/WebstormProjects/veneer"
HEAD_SHA=$(git -C "$VENEER" rev-parse --short HEAD)
cd "C:/Users/mikes/WebstormProjects/scaffold" || exit 9
timeout 7200 codex exec --json -C "$VENEER" --sandbox workspace-write --model gpt-6-astra -c 'model_reasoning_effort="high"' --output-last-message "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/cl7-last.md" "You are the sol role on Astra, the sole writer in this checkout, C:/Users/mikes/WebstormProjects/veneer, whose HEAD is $HEAD_SHA (the CL6 landing commit) and whose tracked tree is clean. Open and follow ./tmp/units/cl7-brief-2.md exactly; it is the effective brief over ./tmp/units/cl7-brief.md, which you also open and follow for every section brief 2 does not change; together they are the whole assignment, and they name the law to read from C:/Users/mikes/WebstormProjects/scaffold before editing. Three retained records sit beside them and you read all three before editing: ./tmp/units/cl7-scout-report.md is the terrain map of the container key, the breakpoint ramp, the case tables, and the deferral rows; ./tmp/units/cl7-rulings.md is the Orchestrator's three rulings; ./tmp/units/cl7-scope-read-report.md is the scope read whose amendments brief 2 folds in. The map's line citations into src/styles/_mixins.scss and tests/setupStyles.ts are stale after CL6, so re-locate every declaration by its name in the current tree rather than by the map's line number; every fact the map states was re-confirmed. Four things decide this unit and the briefs state all four: the ramp already covers every media condition the key carries, so no new ramp member is needed; the navigation combinators ship rather than being excluded; the container widths and the gutter take tokens of their own, and the space scale's twelfth member carries the gutter's value today with exactly two consumers named in the scope read, which you measure before and after; and the key carries two custom properties, so it is not admitted to the shipped set by the empty-properties branch and needs variable rows with proofs. A standing proof sweeps every partial under src/styles for a declaration block shared by two partials, and that population includes the mixins file itself, so brief 2 grants that file for a mixin a shared block needs and for nothing else. The user has ruled that this family is the baseline and conformance is the deliverable: every selector the key carries ends shipped, excluded with a recorded reason, or recorded as a departure, and none ends unaccounted for. You are the bench engine reading the brief inside your own CLI: perform the assignment directly and spawn nothing. Write the report the brief names at ./tmp/units/cl7-report.md and return its full content as your final message, nothing else." < /dev/null > "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl7.jsonl" 2> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl7.err"
echo "exit=$?" >> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl7.err"
