#!/usr/bin/env bash
# Unit CL8 brief 3 on Astra, the sole writer in the Veneer checkout: the second scope correction —
# grant tests/setupConformance.test.ts for the one assertion that enumerates every component with
# guide rows — and then the gate chain green on both engines, including the setup-browser and guide
# gates the earlier stop never reached. The brief is staged at veneer/tmp/units/cl8-brief-3.md
# (copied from scaffold/tmp/units and verified identical before launch) over cl8-brief-2.md and
# cl8-brief.md, with the terrain map, the scope read, and both stop reports beside them. The report
# is written inside the unit's own root at tmp/units/cl8-report-3.md and returned as the last
# message. Journal: tmp/codex/cl8-3.jsonl.
# Cap: 2 hours. The remaining work is one line plus the gate chain on two engines; the observed
# chain cost in this checkout is roughly fifteen minutes, and the cap carries slack against a
# cap-kill reading as a failure.
VENEER="C:/Users/mikes/WebstormProjects/veneer"
HEAD_SHA=$(git -C "$VENEER" rev-parse --short HEAD)
cd "C:/Users/mikes/WebstormProjects/scaffold" || exit 9
timeout 7200 codex exec --json -C "$VENEER" --sandbox workspace-write --model gpt-6-astra -c 'model_reasoning_effort="high"' --output-last-message "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8-3-last.md" "You are the sol role on Astra, the sole writer in this checkout, C:/Users/mikes/WebstormProjects/veneer, whose HEAD is $HEAD_SHA (the CL7 landing commit) and whose working tree carries your own authored CL8 work from both earlier runs. That work is your output, not drift: continue from it rather than starting over. Open and follow ./tmp/units/cl8-brief-3.md exactly; it is the effective brief over ./tmp/units/cl8-brief-2.md and ./tmp/units/cl8-brief.md beneath it, which you also open and follow for every section brief 3 does not change; together they are the whole assignment, and they name the law to read from C:/Users/mikes/WebstormProjects/scaffold before editing. Four retained records sit beside them: ./tmp/units/cl8-scout-report.md the terrain the briefs supersede where they differ, ./tmp/units/cl8-scope-read-report.md the scope read of brief 1, and your own stop reports ./tmp/units/cl8-report.md and ./tmp/units/cl8-report-2.md, which brief 3 answers. You stopped correctly both times and both defects were the Orchestrator's. Brief 3 grants tests/setupConformance.test.ts for one assertion only — the component set in the case named for skipping obligations whose proof cell is a dash, which enumerates every component carrying guide rows as a literal and which CL7 had the same grant for. tests/setupConformance.ts itself stays off-limits. Two things decide this run. The precision reading you flagged is resolved and is not a defect: the Orchestrator compiled the styles entry unminified and the source emits exactly the recorded percentage, so the shorter value comes from the build's CSS minifier and would round Bootstrap's own distribution the same way — do not change the partial's arithmetic, do not add a value-equality gate over the built cascade, and do not tighten a shipped tolerance. And the gate chain must reach green whole, including the browser-setup and guide gates the stop never reached, on managed Chromium and on Edge. If a gate fails for a reason inside your owned scope you fix it and say what you fixed; if one fails for a reason outside it you stop and report rather than widening the scope yourself. You are the bench engine reading the brief inside your own CLI: perform the assignment directly and spawn nothing. Write the report brief 3 names at ./tmp/units/cl8-report-3.md and return its full content as your final message, nothing else." < /dev/null > "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8-3.jsonl" 2> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8-3.err"
echo "exit=$?" >> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8-3.err"
