#!/usr/bin/env bash
# Unit CL8 brief 2 on Astra, the sole writer in the Veneer checkout: the scope correction the stop
# required — extract the declaration blocks the grid shares with the container into _mixins.scss,
# keeping the container's emitted CSS unchanged — and then the work brief 1's scope blocked: the
# red-then-green control, the browser readings, the conformance run, and the full gate chain.
# The brief is staged at veneer/tmp/units/cl8-brief-2.md (copied from scaffold/tmp/units and
# verified identical before launch) over cl8-brief.md, with the terrain map, the scope read, and the
# unit's own stop report beside them. The report is written inside the unit's own root at
# tmp/units/cl8-report-2.md and returned as the last message. Journal: tmp/codex/cl8-2.jsonl.
# Cap: 3 hours. The authored work is already in the tree, so this run is the extraction plus the
# gate chain on two engines; the cap matches brief 1's rather than shrinking on an assumption.
VENEER="C:/Users/mikes/WebstormProjects/veneer"
HEAD_SHA=$(git -C "$VENEER" rev-parse --short HEAD)
cd "C:/Users/mikes/WebstormProjects/scaffold" || exit 9
timeout 10800 codex exec --json -C "$VENEER" --sandbox workspace-write --model gpt-6-astra -c 'model_reasoning_effort="high"' --output-last-message "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8-2-last.md" "You are the sol role on Astra, the sole writer in this checkout, C:/Users/mikes/WebstormProjects/veneer, whose HEAD is $HEAD_SHA (the CL7 landing commit) and whose working tree carries your own authored CL8 work from the run that stopped. That work is your output, not drift: continue from it rather than starting over. Open and follow ./tmp/units/cl8-brief-2.md exactly; it is the effective brief over ./tmp/units/cl8-brief.md beneath it, which you also open and follow for every section brief 2 does not change; together they are the whole assignment, and they name the law to read from C:/Users/mikes/WebstormProjects/scaffold before editing. Three retained records sit beside them and you read all three before editing: ./tmp/units/cl8-scout-report.md is the terrain map, which the briefs supersede wherever they differ; ./tmp/units/cl8-scope-read-report.md is the scope read of brief 1; and ./tmp/units/cl8-report.md is your own stop report, which brief 2 answers point by point. You stopped correctly and the defect was the Orchestrator's: brief 1 told you to follow the container's gutter-alias pattern, which is itself a shared declaration block, and then withheld the file that pattern lives in. Brief 2 grants src/styles/components/_container.scss for replacing its shared blocks with mixin calls and grants src/styles/_mixins.scss outright for the extracted mixins, and nothing else changes in the scope. Two things decide this run. The container's emitted CSS must not change, and you prove that by comparing the built cascade's container declarations before and after the extraction rather than by asserting it — if a declaration moves, order included, you stop and report instead of adjusting the container to match. And every obligation brief 1 left authored but unverified now runs: the red-then-green control on an emitted grid value, the browser readings including the row-column-count against numbered-column cascade behaviour you flagged, the conformance run that decides whether the guide's selector, variable, and deferral rows are the rows the machinery requires, and the full gate chain on managed Chromium with the styles project also on Edge. Your flagged reading about the row carrying no row-gap declaration of its own is correct and brief 2 confirms it; keep it and do not add a declaration the baseline does not carry. You are the bench engine reading the brief inside your own CLI: perform the assignment directly and spawn nothing. Write the report brief 2 names at ./tmp/units/cl8-report-2.md and return its full content as your final message, nothing else." < /dev/null > "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8-2.jsonl" 2> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8-2.err"
echo "exit=$?" >> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8-2.err"
