#!/usr/bin/env bash
# Unit CL8 on Astra, the sole writer in the Veneer checkout: the grid layout rules — the row, its
# column children, the row-column counts, the columns, and the offsets — reading the gutter tokens
# the container already publishes. The brief is staged at veneer/tmp/units/cl8-brief.md (copied
# from scaffold/tmp/units and verified identical before launch), with the terrain map and the scope
# read beside it; the report is written inside the unit's own root at cl8-report.md and
# returned as the last message. Journal: tmp/codex/cl8.jsonl.
# Cap: 3 hours. Observed high mark for a comparable writer exec in this campaign is about 25
# minutes for one key with a retune; CL8 carries three keys, a new partial, a new proof, and the
# gate chain on two engines, plus slack against a cap-kill reading as a failure.
VENEER="C:/Users/mikes/WebstormProjects/veneer"
HEAD_SHA=$(git -C "$VENEER" rev-parse --short HEAD)
cd "C:/Users/mikes/WebstormProjects/scaffold" || exit 9
timeout 10800 codex exec --json -C "$VENEER" --sandbox workspace-write --model gpt-6-astra -c 'model_reasoning_effort="high"' --output-last-message "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/cl8-last.md" "You are the sol role on Astra, the sole writer in this checkout, C:/Users/mikes/WebstormProjects/veneer, whose HEAD is $HEAD_SHA (the CL7 landing commit) and whose tracked tree is clean. Open and follow ./tmp/units/cl8-brief.md exactly; it is the whole assignment, and it names the law to read from C:/Users/mikes/WebstormProjects/scaffold before editing. Two retained records sit beside it and you read both before editing: ./tmp/units/cl8-scout-report.md is the terrain map of the six grid and gutter keys, and ./tmp/units/cl8-scope-read-report.md is the scope read of this brief. The brief supersedes the map wherever they differ, because the Orchestrator re-measured the inventory directly and the map was wrong in places. Four things decide this unit and the brief states all four. The pinned inventory keys by class prefix, so two of your keys are buckets: the row key carries the grid row's rules and also every row-gap utility, and the col key carries the grid columns and also three form-label classes — you ship the grid selectors only, and record the rest as deferred with the reason and the unit that closes each. Veneer ships logical properties and proves the physical resolution in the browser, the way the container partial and its proof already do, so read that partial before writing. This unit adds no token: the gutter tokens already exist, and column widths and offsets are percentages of the grid's own division rather than a retunable scale. And every generated family is driven by one loop over a shared list, never written out, because the styles rule bars repeating per-variant blocks. The user has ruled that this family is the baseline and conformance is the deliverable: every selector a key carries ends shipped, excluded with a recorded reason, or recorded as a departure, and none ends unaccounted for. Shipping a selector into the wrong partial so that a key joins the listed set is the opposite of that, so do not do it. You are the bench engine reading the brief inside your own CLI: perform the assignment directly and spawn nothing. Write the report the brief names at ./tmp/units/cl8-report.md and return its full content as your final message, nothing else." < /dev/null > "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8.jsonl" 2> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8.err"
echo "exit=$?" >> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8.err"
