#!/usr/bin/env bash
# Unit CL8b on Astra, the sole writer in the Veneer checkout: the gutter and gap step utilities —
# the g, gx, gy, and row-gap keys — from a step scale of their own, closing the row key by shipping
# the selectors CL8 deferred to this unit and deleting those deferral rows. The brief is staged at
# veneer/tmp/units/cl8b-brief.md (copied from scaffold/tmp/units and verified identical before
# launch), with the rulings and the scope read beside it. The report is written inside the unit's own
# root at tmp/units/cl8b-report.md and returned as the last message.
# Journal: tmp/codex/cl8b.jsonl.
# Cap: 3 hours. CL8's comparable writer runs took roughly fifteen minutes to half an hour each plus
# the gate chain on two engines; CL8b adds tokens and four keys, and the cap carries slack against a
# cap-kill reading as a failure.
VENEER="C:/Users/mikes/WebstormProjects/veneer"
HEAD_SHA=$(git -C "$VENEER" rev-parse --short HEAD)
cd "C:/Users/mikes/WebstormProjects/scaffold" || exit 9
timeout 10800 codex exec --json -C "$VENEER" --sandbox workspace-write --model gpt-6-astra -c 'model_reasoning_effort="high"' --output-last-message "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8b-last.md" "You are the sol role on Astra, the sole writer in this checkout, C:/Users/mikes/WebstormProjects/veneer, whose HEAD is $HEAD_SHA (the CL8 landing commit) and whose tracked tree is clean. Open and follow ./tmp/units/cl8b-brief.md exactly; it is the whole assignment, and it names the law to read from C:/Users/mikes/WebstormProjects/scaffold before editing. Two retained records sit beside it and you read both before editing: ./tmp/units/cl8b-rulings.md carries the reasoning behind the brief's rulings and the measurements they rest on, and ./tmp/units/cl8b-scope-read-report.md is the scope read of this brief. Four things decide this unit and the brief states all four. The step utilities take a scale of their own carrying no density factor, because every Veneer space token is multiplied by that factor while the gutter tokens are not, so reading the space scale would make a utility and the default it overrides resolve to different lengths at any density but the identity. The gutter classes ship as Bootstrap groups them, two rules per step — the combined class grouped with the horizontal-only class in one rule and with the vertical-only class in the other — because the record carries each combined class twice and Bootstrap's own distribution shows that faithful rather than flattened; a single rule per step would resolve identically in a browser and would still redden the emitted-vocabulary proof CL8 retained, which compares a multiset. You close the row key by shipping the selectors CL8 deferred to this unit and deleting those deferral rows as you ship each name. And the gap and column-gap keys are not yours: they are the same mechanism and the same scale, but no Content/layout key requires them, so shipping them here would move the family's exit criterion. Read src/styles/components/_grid.scss and tests/src/styles/components/grid.test.ts first; they are the pattern, and the single loop over the ramp with an empty infix at the zero boundary is the shape this unit repeats. The user has ruled that this family is the baseline and conformance is the deliverable: every selector a key carries ends shipped, excluded with a recorded reason, or recorded as a departure, and none ends unaccounted for. You are the bench engine reading the brief inside your own CLI: perform the assignment directly and spawn nothing. Write the report the brief names at ./tmp/units/cl8b-report.md and return its full content as your final message, nothing else." < /dev/null > "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8b.jsonl" 2> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8b.err"
echo "exit=$?" >> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8b.err"
