#!/usr/bin/env bash
# Unit CL8b brief 2 on Astra, the sole writer in the Veneer checkout: the correction the unit's stop
# earned. Brief 1 asserted that the recorded row component does not carry the gap entries; it carries
# all thirty-six of them, and the row and row-gap pair is the only overlap among the tuple's
# candidate members. So the recorded key tuple gains g, gx, and gy and not row-gap, and the unit then
# finishes the gates brief 1's stop left unrun. The brief is staged at
# veneer/tmp/units/cl8b-brief-2.md (copied from scaffold/tmp/units and verified identical before
# launch) over cl8b-brief.md, with the rulings, the scope read, and the unit's own stop report beside
# them. The report is written inside the unit's own root at tmp/units/cl8b-report-2.md and returned
# as the last message. Journal: tmp/codex/cl8b-2.jsonl.
# Cap: 2 hours. The remaining work is one tuple edit plus the controls and the gate chain on two
# engines; the observed chain cost in this checkout is roughly fifteen minutes, with slack against a
# cap-kill reading as a failure.
VENEER="C:/Users/mikes/WebstormProjects/veneer"
HEAD_SHA=$(git -C "$VENEER" rev-parse --short HEAD)
cd "C:/Users/mikes/WebstormProjects/scaffold" || exit 9
timeout 7200 codex exec --json -C "$VENEER" --sandbox workspace-write --model gpt-6-astra -c 'model_reasoning_effort="high"' --output-last-message "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8b-2-last.md" "You are the sol role on Astra, the sole writer in this checkout, C:/Users/mikes/WebstormProjects/veneer, whose HEAD is $HEAD_SHA (the CL8 landing commit) and whose working tree carries your own authored CL8b work from the run that stopped. That work is your output, not drift: continue from it rather than starting over. Open and follow ./tmp/units/cl8b-brief-2.md exactly; it is the effective brief over ./tmp/units/cl8b-brief.md beneath it, which you also open and follow for every section brief 2 does not change; together they are the whole assignment, and they name the law to read from C:/Users/mikes/WebstormProjects/scaffold before editing. Three retained records sit beside them and you read all three: ./tmp/units/cl8b-rulings.md, ./tmp/units/cl8b-scope-read-report.md, and your own stop report ./tmp/units/cl8b-report.md, which brief 2 answers. You stopped correctly and the fact you refuted was wrong: brief 1 said the recorded row component does not carry the gap entries, and it carries all thirty-six of them. The error was the Orchestrator's and it contradicted a measurement already in this campaign's own plan, so nothing you authored is in question. The correction is measured and narrow. The row and row-gap pair is the only overlap among the tuple's candidate members and it is complete, so the recorded key tuple gains g, gx, and gy and NOT row-gap — naming row-gap beside row counts each of those selectors twice against a cascade emitting each once. Remove row-gap from the tuple you extended and leave the rest of that edit in place, including the collector prefix extension, which must admit the three gutter prefixes and needs nothing for row-gap because that already matches through the row alternative. Two of your own choices are confirmed and you do not revisit them: the important priority, because Bootstrap emits it for these utilities, no rule bars it, and the link partial already uses it where Bootstrap does; and the utilities placement with its own cascade layer and a step token per step carrying no density factor. Then finish what the stop left unrun: the conformance run that closes the row key, the two-direction control on the extended assertion, the browser proofs you authored, the emitted-value control, and the full gate chain on managed Chromium with the styles, browser-setup, and app-browser projects also on Edge. You are the bench engine reading the brief inside your own CLI: perform the assignment directly and spawn nothing. Write the report brief 2 names at ./tmp/units/cl8b-report-2.md and return its full content as your final message, nothing else." < /dev/null > "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8b-2.jsonl" 2> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8b-2.err"
echo "exit=$?" >> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl8b-2.err"
