#!/usr/bin/env bash
# Unit CL9 on Astra, the sole writer in the Veneer checkout: the table key — the base table with its
# cells and sections, the bordered, borderless, striped, striped-columns, active and hover variants,
# the contextual variants, the group divider, the caption class, and the responsive wrappers. It is
# the first production consumer of the downward breakpoint mixin, and it teaches the
# emitted-vocabulary comparison the downward equivalence, which is arithmetic rather than a string
# rewrite. The brief is staged at veneer/tmp/units/cl9-brief.md (copied from scaffold/tmp/units and
# verified identical before launch), with the terrain record and the scope read beside it. The brief
# restates no measurement: the terrain record is the single home for those. The report is written
# inside the unit's own root at tmp/units/cl9-report.md and returned as the last message.
# Journal: tmp/codex/cl9.jsonl.
# Cap: 3 hours. The table key is dense per selector rather than broad, and the unit also teaches the
# comparison a new equivalence with three controls and runs the gate chain on two engines; comparable
# writer runs in this campaign took fifteen minutes to half an hour, and the cap carries slack
# against a cap-kill reading as a failure.
VENEER="C:/Users/mikes/WebstormProjects/veneer"
HEAD_SHA=$(git -C "$VENEER" rev-parse --short HEAD)
cd "C:/Users/mikes/WebstormProjects/scaffold" || exit 9
timeout 10800 codex exec --json -C "$VENEER" --sandbox workspace-write --model gpt-6-astra -c 'model_reasoning_effort="high"' --output-last-message "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl9-last.md" "You are the sol role on Astra, the sole writer in this checkout, C:/Users/mikes/WebstormProjects/veneer, whose HEAD is $HEAD_SHA (the CL8b landing commit) and whose tracked tree is clean. Open and follow ./tmp/units/cl9-brief.md exactly; it is the whole assignment, and it names the law to read from C:/Users/mikes/WebstormProjects/scaffold before editing. Two retained records sit beside it and you read both before editing: ./tmp/units/cl9-terrain.md and ./tmp/units/cl9-scope-read-report.md. Read the terrain record first and read it carefully, because the brief deliberately restates none of its measurements. That separation is the campaign's own correction: a brief earlier here restated a measurement, the copy drifted from the original, and the unit reading the record cold was the only reader positioned to refuse. So the terrain record is the single home for every count, family, media condition, property, and boundary this unit needs, and if the brief and the record ever disagree the record and the tree win and you stop and report the disagreement rather than resolving it. Four things decide this unit and the brief states all four. Every breakpoint-scoped selector this key carries is recorded under a maximum width, so its families use the downward breakpoint mixin and you are its first production consumer. Veneer's downward mixin stays as it is: it emits the modern range form where the record carries the older maximum-width spelling with a fractional boundary, the two select the same viewports, and the equivalence belongs in the comparison rather than in the emission. That equivalence is arithmetic rather than a string rewrite, and teaching it to the emitted-vocabulary comparison is yours — the brief names both edit sites by symbol and names an adjacent helper that reads either spelling but discards the direction, so it is not a drop-in. And the caption class ships here because the record carries it under this key alone, so no other unit would ever carry it and deferring it would leave it unaccounted. The user has ruled that this family is the baseline and conformance is the deliverable: every selector a key carries ends shipped, excluded with a recorded reason, or recorded as a departure, and none ends unaccounted for. You are the bench engine reading the brief inside your own CLI: perform the assignment directly and spawn nothing. Write the report the brief names at ./tmp/units/cl9-report.md and return its full content as your final message, nothing else." < /dev/null > "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl9.jsonl" 2> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl9.err"
echo "exit=$?" >> "C:/Users/mikes/WebstormProjects/scaffold/tmp/codex/cl9.err"
