# plan-marker-2.py: move the intersession marker after the engine session's first records (E1 to E4) and record this session's in-flight units and pending shared changes. Anchor-refusing.
import sys
def edit(path, old, new):
    s=open(path).read(); n=s.count(old)
    if n!=1: sys.exit(f'edit refused: anchor count {n} in {path} for {old[:60]!r}')
    open(path,'w').write(s.replace(old,new))
P='/home/user/scaffold/.orkestrel/veneer/plan.md'
edit(P, "**Marker.** Veneer `origin/main` `e4e6a40`, scaffold `origin/main` `e5d9ab6`, read 2026-09-23.\nThe engine session has recorded no landing and no `engine/` record yet; move this marker at every\nboundary the protocol names.",
"**Marker.** Veneer `origin/main` `376d84a`, scaffold `origin/main` `0b9d5eb`, read 2026-09-23 at\n16:00 UTC. The engine session's records sit under `engine/` (its plan, `engine/decisions.md` with E1\nto E4, and its terrain record); its landing on Veneer `main` since the previous marker is `376d84a`\n(the removal of `prompt.txt`, E4). Under E4 it works on `main` in both repositories, so every landing\nhere merges `origin/main` into the session branch before the push and `main` is fast-forwarded from\nthe merge result. Its in-flight work at this reading: the J-ENGINE design round (`planner` and\n`analyst`, blind on `engine/units/j-engine-design-brief.md`), with no writing unit dispatched and no\nVeneer file owned; its pending shared changes: none recorded. Move this marker at every boundary the\nprotocol names.")
edit(P, "**In flight (this session).** NAV round 2 (`/home/user/veneer-nv`), DROPDOWN round 2\n(`/home/user/veneer-dd`), COLLAPSE round 2 (returned, awaiting its landing check and DROPDOWN's\nlanding), UTIL-SPACER round 2 (returned, in audit), CONDITIONS (`/home/user/veneer-cn`), ALERT\n(`/home/user/veneer-al`), and CAROUSEL (`/home/user/veneer-ca`). Each owns",
"**In flight (this session).** The disclosure landing: DROPDOWN (`a1b12ab`), NAV (`77bb770`), and\nCOLLAPSE (`041925c`) on the session branch over `e4e6a40`, fast gates green, the verification chain\nand the landing check running, the fold and the push pending. UTIL-DISPLAY (`/home/user/veneer-ud`)\nand UTIL-PLACEMENT (`/home/user/veneer-upl`) on `opus` from `e4e6a40`. ALERT round 2 returned and\nin audit (`/home/user/veneer-al`). CAROUSEL round 2 on `opus` (`/home/user/veneer-ca`). CONDITIONS\nand UTIL-SPACER landed (`8ca1609`, `746d3e9`). Each unit owns")
edit(P, "**Pending shared changes.** `tests/setup.ts` gains `CASCADE_KEYS` rows, `DRIVEN_KEYS` rows, and\n`CaptureSubject` members with each landing, append-only at the registry's end.",
"**Pending shared changes.** The disclosure landing appends the dropdown, nav, and collapse\n`CASCADE_KEYS` rows, the dropdown and nav `DRIVEN_KEYS` rows, and their `CaptureSubject` members to\n`tests/setup.ts`, and adds the Collapse, Dropdown, Tab, and ScrollSpy `plugin` rows with\n`Owner: J-ENGINE.` to `guides/veneer.md`; the ALERT and CAROUSEL landings follow with the same shape.\nIn general, `tests/setup.ts` gains `CASCADE_KEYS` rows, `DRIVEN_KEYS` rows, and `CaptureSubject`\nmembers with each landing, append-only at the registry's end.")
print('plan marker moved')
