#!/usr/bin/env bash
# U7e audit, the objective lane on Astra (read-only): rules on ../u7e-audit-claims.md over
# the rendered guide diff u7e-diff.patch.txt and the live Veneer tree at 92aad70. Under the
# user's ruling (audits cover implementation only; guides are the parity minimum) this is the one
# judging lane: it rules whether every changed sentence, row, and cell is true of the landed tree
# and whether the parity gates read what changed. Journal: u7e-audit-analyst.jsonl.
cd "C:/Users/mikes/WebstormProjects/scaffold" || exit 9
timeout 3600 codex exec --json -C "C:/Users/mikes/WebstormProjects/scaffold" --sandbox read-only --model gpt-6-astra -c 'model_reasoning_effort="high"' --output-last-message "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7e-audit-analyst-last.md" "You hold the OBJECTIVE lane (the truth of every changed sentence, row, and cell of guides/veneer.md against the landed tree, and whether each change is the minimum the falsity required) of the audit of unit U7e in the Veneer checkout at C:/Users/mikes/WebstormProjects/veneer (HEAD 92aad70, the U7c landing), written by Opus 5. Under the user's ruling that audits cover implementation only and that guides are the parity minimum, this lane is the round's one judging lane: no subjective lane runs, and you report no wording, register, contraction, or style finding. The claims file ./tmp/audit/u7e-audit-claims.md alone fixes the claim numbers: rule on every claim it carries, and only those, with CONFIRMED, REFUTED, or UNDECIDABLE and the deciding evidence (file:line or exact text). The Orchestrator rendered the guide diff over 92aad70 at ./tmp/audit/u7e-diff.patch and the status at ./tmp/audit/u7e-status.txt; read those, the live guide and the live source and test files each changed sentence describes (app/browser/**, tests/app/browser/**, tests/setup*.ts, src/styles/**, tests/src/styles/**), the retained records under ./.orkestrel/veneer/ (units/u7e-brief.md, units/u7e-report.md, units/u7c-guide-bounds.md, units/prose-bounds-carry.md), and the law under this checkout (AGENTS.md and .claude/rules/documentation.md and writing.md and styles.md). Run no command that writes. Add extra findings only for a changed sentence that is false of the tree, or a sentence one of the brief's bounds names that is false and was left unedited, numbered after the last claim, with a site and the true reading; distinguish a finding that forces another round from one that does not. End with one terminal line: Verdict: accept, or Verdict: fix round with the claims that force it." < /dev/null > "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7e-audit-analyst.jsonl" 2> "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7e-audit-analyst.err"
echo "exit=$?" >> "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7e-audit-analyst.err"
