#!/usr/bin/env bash
# U7f portfolio verdict round 3 (narrow: items 4 and 10), the objective state-truth lane on Astra
# (read-only) with the two Elements focus-ring frames attached. Journal: u7f-verdict-3-analyst.jsonl.
E="C:/Users/mikes/WebstormProjects/scaffold/tmp/capture/elements"
cd "C:/Users/mikes/WebstormProjects/scaffold" || exit 9
timeout 3600 codex exec --json -C "C:/Users/mikes/WebstormProjects/scaffold" --sandbox read-only --model gpt-6-astra -c 'model_reasoning_effort="high"' \
  -i "$E/elements-button-primary-focus-ring--light-1280.png" -i "$E/elements-button-primary-focus-ring--dark-1280.png" \
  --output-last-message "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7f-verdict-3-analyst-last.md" "You hold the OBJECTIVE STATE-TRUTH lane of the U7f portfolio verdict, round 3, which is narrow. Open ./tmp/units/u7f-verdict-brief-3.md: it is the whole assignment, and it names the briefs it supersedes (./tmp/units/u7f-verdict-brief-2.md and ./tmp/units/u7f-verdict-brief.md) and the rulings so far (./.orkestrel/veneer/u7f-verdict.md). The attached images are Elements' padded focus-ring frames at light-1280 and dark-1280 from the round-4 harness. Read the step logs and .txt artifacts under C:/Users/mikes/WebstormProjects/scaffold/tmp/capture/elements/, Veneer's artifacts under C:/Users/mikes/WebstormProjects/veneer/tmp/capture/, the harness report ./.orkestrel/veneer/units/u7f-harness-report-4.md, and Elements' focus declaration at C:/Users/mikes/WebstormProjects/elements/src/styles/surfaces/_focus.scss. Rule item 4 and refer item 10 with evidence and no verdict. Run no command that writes. Your final message is exactly the shape the brief's Output section fixes: one line per item, referrals, one terminal line CONVERGED or ANOTHER ROUND(<items>)." < /dev/null > "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7f-verdict-3-analyst.jsonl" 2> "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7f-verdict-3-analyst.err"
echo "exit=$?" >> "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7f-verdict-3-analyst.err"
