#!/usr/bin/env bash
# U7f portfolio verdict round 2, the objective state-truth lane on Astra (read-only), with the
# curated frame set attached (round 1's set plus Elements' focus-ring and States frames and the
# regenerated Veneer home frames). Journal: u7f-verdict-2-analyst.jsonl.
V="C:/Users/mikes/WebstormProjects/veneer/tmp/capture/states"
E="C:/Users/mikes/WebstormProjects/scaffold/tmp/capture/elements"
cd "C:/Users/mikes/WebstormProjects/scaffold" || exit 9
timeout 3600 codex exec --json -C "C:/Users/mikes/WebstormProjects/scaffold" --sandbox read-only --model gpt-6-astra -c 'model_reasoning_effort="high"' \
  -i "$V/home--light-1280.png" -i "$V/home--dark-1280.png" \
  -i "$V/button-primary-rest--light-1280.png" -i "$V/button-primary-rest-dark--dark-1280.png" -i "$V/button-primary-rest--light-390.png" -i "$V/button-primary-rest-dark--dark-390.png" \
  -i "$V/button-primary-focus--light-1280.png" -i "$V/button-primary-focus-dark--dark-1280.png" -i "$V/button-primary-pressed--light-1280.png" -i "$V/button-primary-pressed-dark--dark-1280.png" \
  -i "$V/button-primary-hover--light-1280.png" -i "$V/button-primary-hover-dark--dark-1280.png" -i "$V/button-primary-active--light-1280.png" -i "$V/button-primary-active-dark--dark-1280.png" \
  -i "$E/elements-button-primary-rest--light-1280.png" -i "$E/elements-button-primary-rest--dark-1280.png" -i "$E/elements-button-primary-focus-ring--light-1280.png" -i "$E/elements-button-primary-focus-ring--dark-1280.png" \
  -i "$E/elements-button-primary-pressed--light-1280.png" -i "$E/elements-button-states--light-1280.png" -i "$E/elements-button-states--dark-1280.png" \
  -i "$E/elements-button-primary-hover--light-1280.png" -i "$E/elements-button-primary-hover--dark-1280.png" -i "$E/elements-button-primary-active--light-1280.png" -i "$E/elements-button-primary-active--dark-1280.png" \
  --output-last-message "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7f-verdict-2-analyst-last.md" "You hold the OBJECTIVE STATE-TRUTH lane of the U7f portfolio verdict, round 2. Open ./tmp/units/u7f-verdict-brief-2.md and the brief it supersedes, ./tmp/units/u7f-verdict-brief.md: together they are the whole assignment, they fix the twelve items you rule on under their round-1 numbers and the fixed verdict shape you return, and they name every artifact; ./.orkestrel/veneer/u7f-verdict.md carries round 1's rulings. The attached images are, in order: Veneer home light-1280, home dark-1280, rest light-1280, rest-dark dark-1280, rest light-390, rest-dark dark-390, focus light-1280, focus-dark dark-1280, pressed light-1280, pressed-dark dark-1280, hover light-1280 (element frame), hover-dark dark-1280 (element), active light-1280 (element), active-dark dark-1280 (element); then Elements rest light-1280, rest dark-1280, focus-ring light-1280 (padded element frame), focus-ring dark-1280, pressed light-1280, states light-1280 (the States section), states dark-1280, hover light-1280 (element), hover dark-1280 (element), active light-1280 (element), active dark-1280 (element). Read the per-variant .txt artifacts, step logs, and console logs from disk on both sides, and any other frame you need by name. Rule items 1 to 10 for state truth against the new portfolio (items proven in round 1 only for regression), and refer 11 and 12 with evidence and no verdict. Run no command that writes. Your final message is exactly the shape the Output section fixes: one line per item, referrals, one terminal line CONVERGED or ANOTHER ROUND(<items>)." < /dev/null > "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7f-verdict-2-analyst.jsonl" 2> "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7f-verdict-2-analyst.err"
echo "exit=$?" >> "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7f-verdict-2-analyst.err"
