#!/usr/bin/env bash
# U7f portfolio verdict, the objective state-truth lane on Astra (read-only), with a curated set of
# frames attached as images (the full portfolio is on disk for the .txt artifacts and any frame the
# lane wants to name; the attached set covers every state in both packages at 1280 plus the 390 rest
# frames). Journal: u7f-verdict-analyst.jsonl.
V="C:/Users/mikes/WebstormProjects/veneer/tmp/capture/states"
E="C:/Users/mikes/WebstormProjects/scaffold/tmp/capture/elements"
cd "C:/Users/mikes/WebstormProjects/scaffold" || exit 9
timeout 3600 codex exec --json -C "C:/Users/mikes/WebstormProjects/scaffold" --sandbox read-only --model gpt-6-astra -c 'model_reasoning_effort="high"' \
  -i "$V/button-primary-rest--light-1280.png" -i "$V/button-primary-rest-dark--dark-1280.png" -i "$V/button-primary-rest--light-390.png" -i "$V/button-primary-rest-dark--dark-390.png" \
  -i "$V/button-primary-focus--light-1280.png" -i "$V/button-primary-focus-dark--dark-1280.png" -i "$V/button-primary-pressed--light-1280.png" -i "$V/button-primary-pressed-dark--dark-1280.png" \
  -i "$V/button-primary-hover--light-1280.png" -i "$V/button-primary-hover-dark--dark-1280.png" -i "$V/button-primary-active--light-1280.png" -i "$V/button-primary-active-dark--dark-1280.png" \
  -i "$E/elements-button-primary-rest--light-1280.png" -i "$E/elements-button-primary-rest--dark-1280.png" -i "$E/elements-button-primary-focus--light-1280.png" -i "$E/elements-button-primary-pressed--light-1280.png" \
  -i "$E/elements-button-primary-hover--light-1280.png" -i "$E/elements-button-primary-hover--dark-1280.png" -i "$E/elements-button-primary-active--light-1280.png" -i "$E/elements-button-primary-active--dark-1280.png" \
  --output-last-message "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7f-verdict-analyst-last.md" "You hold the OBJECTIVE STATE-TRUTH lane of the U7f portfolio verdict. Open ./tmp/units/u7f-verdict-brief.md: it is the whole assignment, it fixes the twelve items you rule on and the fixed verdict shape you return, and it names every artifact. The attached images are, in order: Veneer rest light-1280, rest-dark dark-1280, rest light-390, rest-dark dark-390, focus light-1280, focus-dark dark-1280, pressed light-1280, pressed-dark dark-1280, hover light-1280 (element frame), hover-dark dark-1280 (element frame), active light-1280 (element frame), active-dark dark-1280 (element frame); then Elements rest light-1280, rest dark-1280, focus light-1280, pressed light-1280, hover light-1280 (element), hover dark-1280 (element), active light-1280 (element), active dark-1280 (element). Read the per-variant .txt artifacts, step logs, and console logs from disk at the paths the brief names, and any other frame you need by name. Rule whether each frame shows the state its name and the step log claim, whether the readings and the ARIA snapshots agree with the frames, and whether any frame is a harness artefact rather than the surface; rule items 1 to 10, and refer 11 and 12 with evidence and no verdict. Run no command that writes. Your final message is exactly the shape the brief's Output section fixes: one line per item, referrals, one terminal line CONVERGED or ANOTHER ROUND(<items>)." < /dev/null > "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7f-verdict-analyst.jsonl" 2> "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7f-verdict-analyst.err"
echo "exit=$?" >> "C:/Users/mikes/WebstormProjects/scaffold/.orkestrel/veneer/units/u7f-verdict-analyst.err"
